### ISSUE TITLE
Correcting invitable synchronization with omniauthable?

### ISSUE THREAD

**Issue by daidekman** [scambra/devise_invitable#177]
Thanks for creating such a great tool with invitable.

I have been using Devise with omniauth (primarily for Facebook login) and now I am seeking to implement invitations, yet not lose the omniauth login functionality.  My goal is to allow a user to accept an invitation, then have the option to register/login using omniauth or the password confirmation fields that already exist.

I know to edit "/views/devise/invitations/edit.html.erb" so that there is a link to the omniauth_authorize_path.  However, how would this authorization retain the checks on the invitation token? With omniauth we would still need to ensure a valid invitation_token and record the invited_by.

Many thanks for your help!
-Dave

**Comment by Onumis** [comment]
This is quite old already, but just FYI, you can add params to omniauth stages:

A link generated with:
```
<%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_url(invitation_token: params[:invitation_token] ) %>
```

Will give you access to the `invitation_token` in `request.env['omniauth.params']` on the callback action.
