### ISSUE TITLE
Routing Error

### ISSUE THREAD

**Issue by khanhnguyen** [scambra/devise_invitable#198]
When I hit "Send an invitation". it show this issue. please help me solved my problem. 

Routing Error
No route matches [POST] "/invitations/user"

**Comment by leekesler** [comment]
Getting the same error. I'm using the default controller.

# route.rb
Rails.application.routes.draw do
    ....
      devise_for :users, path: "",
                     path_names: { sign_in: "login", sign_out: "logout", registration: "profile" },
                     controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" } # sessions: "users/sessions", passwords: "users/passwords"
  
  devise_scope :user do
    resources :invitations
  end

  ....

**Comment by belumarek** [comment]
Getting the same error. I'm using the default controller.

**Comment by scambra** [comment]
Tests are passing, more info is needed so I can reproduce it.

Output for rails routes may help to find out why route is not recognized
