### ISSUE TITLE
Bad accept invitation route

### ISSUE THREAD

**Issue by standingwave** [scambra/devise_invitable#202]
The automatically generated route for accept_user_invitation_url is not working for me.  My setup is pretty vanilla and all of my other routes and devise setup are working just fine.  However, the accept_user_invitation_url has an extraneous "." in it that is clearly breaking the route.

Example accept_user_invitation_url:
http://default.lvh.me:5000/users/invitation/accept.?invitation_token=DvTzf2eKyLtCDLojVanM

From routes.rb:
devise_for :users, :controllers => { :sessions => "admin/sessions", :registrations => "admin/registrations", :confirmations => "admin/confirmations", :invitations => "invitations" }

From rake routes:
accept_user_invitation GET    /users/invitation/accept(.:format)                               invitations#edit

Anyone else seeing this same behavior?

**Comment by gabrielhilal** [comment]
I have the same problem: `http://localhost:3000/api/auth/invitation/accept.2?invitation_token=dr8xXsXdUa2FFjxUe6e8`

It is adding the id (2) in the url.
