### ISSUE TITLE
Customize the Redirect after Accepting an Invite

### ISSUE THREAD

**Issue by bhellman1** [scambra/devise_invitable#32]
Hello, after a user accepts an invitation and signs up the flash notice "Your password was set successfully. You are now signed in." appears.

How can you customize that msg and redirect to a different URL, I would like to redirect to /gettingstarted

thanks

**Comment by isabel-thx** [comment]
Hi there, I realized that the path has changed and I tried to override the helper method after_accept_path_for but it doesn't seem to work. Is there another way to redirect the user?
