### ISSUE TITLE
invalid token after upgrade devise invitable

### ISSUE THREAD

**Issue by mtorres-ix** [scambra/devise_invitable#402]
hi guys I have a problem, after that I upgrade 1.1.8 to the last version of devise invitable I started to get this error when I send an invitation, by the way I upgrade the fields and I added the new one

```
http://localhost:3000/customer/invitation/accept?invitation_token=b3ace9682649dd2f09d0c6cb81be0bb546026a451d24ac9c7c86dab5eca70af8
```

I get

```
The invitation token provided is not valid!
```

any idea?

**Comment by equivalent** [comment]
I'm witnessing  similar problems like @ghost with similal  gem setup ( 'devise', '~> 3.4.1' , ''devise_invitable', '~> 1.4.0', rails 3.2.20) after upgrading devise & devise invitible version and changed views to use `@token` but my problem is: 

**Given**  invited person received the invitation link with digested token (e.g. `?invitation_token=CzzbEtMo4xS6hcFhuccv`)
**And** Rails succesfully create that user in database with db record `user.invitation_token =="0b2b2a368effc58a341c603f7c2647ea04043fd331a00a07c66f47dd0b31"`
**When** person open the link in browser
**Then** `Devise::InvitationsController#edit` tries to run lookup query `SELECT users.* FROM users WHERE users.invitation_token = '0b2b2a368effc58a341c603f7c2647ea04043fd331a00a07c66f47dd0b3125ae'`
**And** and person is redirected to sign in page with flash message `You need to sign in or sign up before continuing.`  

now please  comparend the SQL query token that devise is trying to reach with  the token in the DB. That token has extra 4 chars at the end (`25ae`) . I've tried this several time all the time the chars are random.

 Anyone have any idea how to fix this pls the "good way" ?

Thank you

**Comment by equivalent** [comment]
same 4 chars here:

```ruby
User.last.invitation_token 
# => "0b2b2a368effc58a341c603f7c2647ea04043fd331a00a07c66f47dd0b31"
 
User.find_by_invitation_token('CzzbEtMo4xS6hcFhuccv', true)
#  User Load (0.2ms)  SELECT `users`.* FROM `users` WHERE `users`.`invitation_token` = '0b2b2a368effc58a341c603f7c2647ea04043fd331a00a07c66f47dd0b3125ae' AND (`users`.`deleted_at` IS NULL) LIMIT 1
# => nil
```

...it seems to me like some sort of Salt

**Comment by equivalent** [comment]
OK solved my problem !! ...brutall ulttra mega giga facepalm in my favor 

```
# db/schema.rb
# ....
   t.string   "invitation_token",       :limit => 60
# ...
```

GAAAAAAAH! :rage2:   :smile:

**Comment by mcbsys** [comment]
Had some confusion on this since the readme section on accepting an invitation doesn't explain that you can only do it with the raw token. 

For writing tests, I found that if I have a user object, I can manually accept the invitation as follows:

    u = User.find_by_email(to_email) # or any other way to get the user you're testing
    u.password = "password"
    u.,accept_invitation!

**Comment by ryanwanger** [comment]
How do you send the raw token if you're sending out the invites programmatically?

user.invite! sends out a link with a 20ish character token but what gets stored in invitation_token in the db is much longer...more like 80 characters.
