### ISSUE TITLE
Avoid sending confirmation email

### ISSUE THREAD

**Issue by jetsekoopmans** [scambra/devise_invitable#422]
I have installed devise_invitable. When someone is invited, two email are sent. One confirmation and one invitation. I want to skip the confirmation email. Can anyone help me?

I have version 1.3.2 of devise_invitable and 3.2.2 of devise

**Comment by twe4ked** [comment]
I had a similar problem, I was calling `save` on the user inside the `invite!` block. Fixed by rearranging some code.
