### ISSUE TITLE
Skipping invitation on a user record doesn't work inside a block

### ISSUE THREAD

**Issue by ahmetabdi** [scambra/devise_invitable#460]
```ruby
resource_class.invite!(invite_params, current_inviter) do |u|
  u.skip_invitation = true
 end
```
skip_invitation gets ignored in the above instance.

Workaround:

```ruby
user.skip_invitation = true
user.invite!
```

**Comment by morgler** [comment]
I think the problem was due to you using an existing instance of a user. This problem was fixed in the merge request by scambra. So I guess this issue can be closed.

**Comment by ahmetabdi** [comment]
Yep that solved it will close.
