### ISSUE TITLE
Inviting Users to an Organization

### ISSUE THREAD

**Issue by farmcp** [scambra/devise_invitable#461]
I currently have two models set up where an `organization` has many `users`. Is there a way to configure this gem such that a `user` can only invite someone to their `organization`?

**Comment by viktorsmari** [comment]
@scambra I am stuck on the same issue. Is there a better way to do it today?
I have one user inviting another user, and they should be in the same organization.

So the inviter has `current_user.organization` and when the invited user gets created I want 
`User.create` to also merge `organization: current_user.organization`

What is the best way to achieve this?

**Comment by scambra** [comment]
Something like that before_create callback should work and looks right

**Comment by frizman21** [comment]
Did you get this to work? Seems like a really common use case. I would love an example of the right way if someone has it!
