### ISSUE TITLE
before_filter skiped by invitation limit alert

### ISSUE THREAD

**Issue by nicka** [scambra/devise_invitable#489]
When the invitation limit is reached `application_controller.rb` before_filters are skipped.

Example:

```
before_filter :load_activities

def load_activities
  @activities = current_user.activities
end
```

`@activities` returns `nil` when the inivtation limit is reached.

Any ideas on this?

**Comment by scambra** [comment]
Closing, using prepend_before_filter is the way Devise adds filters in their controllers too. You should override Invitation Controller to fix this.
