### ISSUE TITLE
Configurable invitation token? 

### ISSUE THREAD

**Issue by kalkov** [scambra/devise_invitable#511]
Hi, we are willing to use shorter invitation token(instead of sha-256), because sometimes the user needs to type it by hand. 
I really like : 

``` ruby
Devise.friendly_token[0, 8]
```

Can you suggest how to customize that?

**Comment by andreiglingeanu** [comment]
@scambra Are you suggesting a simple re-rewrite for the `Devise.token_generator` in an initializer. AFAIK the original one is instantiated right [here](https://github.com/plataformatec/devise/blob/88724e10adaf9ffd1d8dbfbaadda2b9d40de756a/lib/devise/rails.rb#L41).

**Comment by scambra** [comment]
Yes, I was suggesting to rewrite token_generator if he wants to use different tokens to devise default ones. Devise is instantiating token generator if not defined by user.

**Comment by andreiglingeanu** [comment]
@scambra Sounds great. Thank you.

**Comment by andreiglingeanu** [comment]
That's what I am using so far for this. Be sure to execute this in an initializer, _after_ you end up configuring your `config.secret_key`.

```ruby
Devise.setup do |config|
  config.secret_key = 'random_key'

  if secret_key = Devise.secret_key
    Devise.token_generator = Class.new do
      def initialize(key_generator, digest = "SHA256")
        @key_generator = key_generator
        @digest = digest
      end

      def digest(klass, column, value)
        value.present? && OpenSSL::HMAC.hexdigest(@digest, key_for(column), value.to_s)
      end

      def generate(klass, column)
        key = key_for(column)

        loop do
          # configure your length here
          raw = Devise.friendly_token(6)

          enc = OpenSSL::HMAC.hexdigest(@digest, key, raw)
          break [raw, enc] unless klass.to_adapter.find_first({ column => enc })
        end
      end

      private

      def key_for(column)
        @key_generator.generate_key("Devise #{column}")
      end
    end.new(
      ActiveSupport::CachingKeyGenerator.new(ActiveSupport::KeyGenerator.new(secret_key))
    )
  end
end
```

You can change the`Devise.friendly_token(6)` however you want in order to change the strategy for defining your token.

Hey @plataformatec, mind adding a wiki entry for that?

**Comment by andreiglingeanu** [comment]
UPD: this is no longer possible because of this [commit](https://github.com/plataformatec/devise/commit/d122faf410e0d6f7589adf9aa624ea4ee5bff8b9)

**Comment by scambra** [comment]
It's possible, that commit only changes how confirmation_token is generated, devise doesn't save digest token for confirmation, but it saves digest token for reset password, using Devise.token_generator, as devise invitable does for invitation token.

**Comment by andreiglingeanu** [comment]
Hey @scambra! I stumbled upon this issue accidentally and I found useful info in it.

@scambra Yeah, you are right that password reset tokens are not affected by this change.
 I always aimed at customizing `confirmation_token` specifically, that is way I complained.
