### ISSUE TITLE
Customising views within an engine

### ISSUE THREAD

**Issue by soon0009** [scambra/devise_invitable#528]
Hi, I'm using devise_invitable within a rails engine. So far so good but when I try to customise a view it doesn't seem to pick up the customised file within the engine. If I place the customised view in the host app it works fine but I would like to override from within the engine.

**Comment by scambra** [comment]
Are you sure your engine is working? Do you have another views in the engine?

**Comment by soon0009** [comment]
Yeah engine is working. I'm also successfully overriding devise/sessions/new.html.erb and devise/passwords/new.html.erb

**Comment by scambra** [comment]
It's weird, devise invitations controller uses devise methods to render views (respond_with and respond_with_navigational).

**Comment by soon0009** [comment]
I'll have a play around with it. Thanks for the response.

**Comment by soon0009** [comment]
Finally got back on this. I found I needed to require devise and devise_invitable before I required my engine.
