### ISSUE TITLE
Invitation token is invalid when inviting from other model

### ISSUE THREAD

**Issue by arminnaimi** [scambra/devise_invitable#534]
Hi,

I have been having an issue that I can't seem to figure out. I am inviting a user successfully from the Admin model in a namespace. The route is generated successfully and can be accessed without any trouble. The issue arises when the User model submits all form fields and the error "Invitation token is invalid" is raised. The logs do not indicate anything useful, except a 200 OK HTTP request. 

I am using the most recent version of devise_invitable 1.4.1, Rails 4.2.0, Ruby 2.2.0. I have not created my custom invitation controller.

**Comment by scambra** [comment]
You should check query used to load user when open accept invitation url and query used when form is submitted. They should look for user with same token. Also check invitation_token in parameters for these requests.

**Comment by arminnaimi** [comment]
Hi @scambra,

Thanks for taking the time to respond. The token is the same throughout all stages. The invitation_token is passing the invitation_token from the url. It seems all correct. Below are the queries:

Invitation from the backoffice as an Admin

Started POST "/backoffice/accounts/1/invite_users" for 127.0.0.1 at 2015-02-27 14:15:44 +0000
Processing by Backoffice::AccountsController#invite_users as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"/JqDORN04d8Zue/tVCl11vdRa5tmiEFzJETy8s++Ytp9uIGVJPLyzd1B2oFrIzf1BK2QpNtWt+OHhp4Gn+SCng==", "to"=>"armin.naimi@gmail.com", "commit"=>"Invite User", "id"=>"1"}
  Admin Load (0.6ms)  SELECT  "admins".* FROM "admins" WHERE "admins"."id" = $1  ORDER BY "admins"."id" ASC LIMIT 1  [["id", 1]]
  Account Load (0.8ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT 1  [["id", 1]]
  User Load (2.8ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["email", "armin.naimi@gmail.com"]]
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."invitation_token" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["invitation_token", "0245ab4aa3ec57a0eada6a7ef9eab7ceaa278dce14866f9caa9d049776ccdaff"]]
   (0.3ms)  BEGIN
  SQL (3.7ms)  INSERT INTO "users" ("email", "invitation_token", "invitation_created_at", "invitation_sent_at", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["email", "armin.naimi@gmail.com"], ["invitation_token", "0245ab4aa3ec57a0eada6a7ef9eab7ceaa278dce14866f9caa9d049776ccdaff"], ["invitation_created_at", "2015-02-27 14:15:44.529993"], ["invitation_sent_at", "2015-02-27 14:15:44.529993"], ["created_at", "2015-02-27 14:15:44.531652"], ["updated_at", "2015-02-27 14:15:44.531652"]]
   (1.6ms)  COMMIT
  Rendered devise/mailer/invitation_instructions.html.erb (7.0ms)

Devise::Mailer#invitation_instructions: processed outbound mail in 335.3ms

Sent mail to armin.naimi@gmail.com (356.0ms)
Date: Fri, 27 Feb 2015 14:15:44 +0000
From: Telesson <info@careharmony.co.uk>
Reply-To: Telesson <info@careharmony.co.uk>
To: armin.naimi@gmail.com
Message-ID: <54f07c10d9311_c26f3ffd80908c9862250@Armin.mail>
Subject: Invitation instructions
Mime-Version: 1.0
Content-Type: text/html;
 charset=utf-8
Content-Transfer-Encoding: 7bit

<p>Hello armin.naimi@gmail.com</p>

<p>Someone has invited you to http://test.telesson.dev:3000/, you can accept it through the link below.</p>

<p><a href="http://test.telesson.dev:3000/users/invitation/accept?invitation_token=zCyYCr9XxDswzh9qnUix">Accept invitation</a></p>

<p>If you don't want to accept the invitation, please ignore this email.<br />Your account won't be created until you access the link above and set your password.</p>

Redirected to http://telesson.dev:3000/backoffice/accounts/1
Completed 302 Found in 996ms (ActiveRecord: 12.1ms)

After user clicked on invitation

   Started GET "/users/invitation/accept?invitation_token=zCyYCr9XxDswzh9qnUix" for 127.0.0.1 at 2015-02-27 14:16:27 +0000
Processing by Devise::InvitationsController#edit as HTML
  Parameters: {"invitation_token"=>"zCyYCr9XxDswzh9qnUix"}
  User Load (1.8ms)  SELECT  "users".* FROM "users" WHERE "users"."invitation_token" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["invitation_token", "0245ab4aa3ec57a0eada6a7ef9eab7ceaa278dce14866f9caa9d049776ccdaff"]]
  Account Load (0.8ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."subdomain" = $1  ORDER BY "accounts"."id" ASC LIMIT 1  [["subdomain", "test"]]
  Account Load (0.6ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."subdomain" = $1 LIMIT 1  [["subdomain", "test"]]
  Status Load (0.6ms)  SELECT  "statuses".* FROM "statuses" WHERE "statuses"."statusable_id" = $1 AND "statuses"."statusable_type" = $2 LIMIT 1  [["statusable_id", 1], ["statusable_type", "Account"]]
  Rendered devise/invitations/edit.html.erb within layouts/devise (74.1ms)
Completed 200 OK in 222ms (Views: 196.9ms | ActiveRecord: 3.8ms)

After form fields are filled in and submitted

Started PUT "/users/invitation" for 127.0.0.1 at 2015-02-27 14:18:24 +0000
Processing by Devise::InvitationsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"yZ/t5CZ6Ui3Uyb784/SEMslyMCWY0tmbsVOoaS/9I6A4bnkU4Vo0PmZecBjhxizf4Cxi7F7hkLoOviJpMbDMtg==", "user"=>{"invitation_token"=>"zCyYCr9XxDswzh9qnUix", "title"=>"Mr", "name"=>"Armin Naimi", "organisation"=>"Test", "team"=>"Team", "phone_number"=>"07445188279", "landline_number"=>"07445188279", "email"=>"armin.naimi@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Create account"}
  Account Load (1.5ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."subdomain" = $1  ORDER BY "accounts"."id" ASC LIMIT 1  [["subdomain", "test"]]
  Account Load (1.0ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."subdomain" = $1 LIMIT 1  [["subdomain", "test"]]
  Status Load (0.7ms)  SELECT  "statuses".* FROM "statuses" WHERE "statuses"."statusable_id" = $1 AND "statuses"."statusable_type" = $2 LIMIT 1  [["statusable_id", 1], ["statusable_type", "Account"]]
  User Load (1.1ms)  SELECT  "users".* FROM "users" WHERE "users"."account_id" = $1 AND "users"."invitation_token" = $2  ORDER BY "users"."id" ASC LIMIT 1  [["account_id", 1], ["invitation_token", "0245ab4aa3ec57a0eada6a7ef9eab7ceaa278dce14866f9caa9d049776ccdaff"]]
  Rendered devise/invitations/edit.html.erb within layouts/devise (36.3ms)
Completed 200 OK in 113ms (Views: 77.3ms | ActiveRecord: 4.2ms)

**Comment by scambra** [comment]
Try next in rails console:

    user = User.find_by_invitation_token('zCyYCr9XxDswzh9qnUix', false)
    user.valid_invitation?

**Comment by arminnaimi** [comment]
Tried that and here is my console output: 

2.2.0 :006 > user = User.find_by_invitation_token('bqRrRCKsygBHMGjyob6p', false)
  User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."invitation_token" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["invitation_token", "e2d7204fefd8946f45b9b402cfdfb6bc3c386e6ac6c4251f89b6535a50aeab2d"]]
 => #<User id: 2, name: nil, email: "armin.naimi@gmail.com", encrypted_password: "", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, created_at: "2015-02-27 16:57:01", updated_at: "2015-02-27 16:57:01", organisation: nil, phone_number: nil, landline_number: nil, team: nil, title: nil, admin: false, account_id: nil, invitation_token: "bqRrRCKsygBHMGjyob6p", invitation_created_at: "2015-02-27 16:57:01", invitation_sent_at: "2015-02-27 16:57:01", invitation_accepted_at: nil, invitation_limit: nil, invited_by_id: nil, invited_by_type: nil, invitations_count: 0> 
2.2.0 :007 > user.valid_invitation?
 => true 
2.2.0 :008 >

**Comment by scambra** [comment]
User.find_by_invitation is used by accept_invitation!, and sets "invitation token is invalid", if user.valid_invitation? returns true is not must be set. You can ensure it returns a record without error with:

    user.errors.to_a

If it returns empty array, then you can try to debug accept_invitation! overriding some methods in your model. For example:

```ruby
class User < ActiveRecord::Base
  ...
  def self.find_by_invitation_token(*)
    super.tap do |record|
      logger.debug record.inspect
      logger.debug record.errors.to_a.inspect
    end
  end
end
```

**Comment by jetaggart** [comment]
I'm having the same issue. I may be wrong, but it seems like these two lines of code are contradictory: 
https://github.com/scambra/devise_invitable/blob/c0ae7b58141a35a7cba22504703277402c369e1a/lib/devise_invitable/model.rb#L286
and
https://github.com/scambra/devise_invitable/blob/c0ae7b58141a35a7cba22504703277402c369e1a/lib/devise_invitable/model.rb#L286

That says to me: If "the user is persisted and has a token?" set the invalid token and if "the user is *not* persisted or *does not* have a token (through valid_invitation?)?", which requires them to be persisted" set the invalid token.

Inlining the `valid_invitation?` logic reads:
```
invitable.errors.add(:invitation_token, :invalid) if invitable.invitation_token && invitable.persisted? && !(invitable.persisted? && invitable.invitation_token.present?)
```

How can a user ever have a valid token?

**Comment by scambra** [comment]
I'm not sure I understand you, because you link same line twice.

     def valid_invitation?
       invited_to_sign_up? && invitation_period_valid?
     end
     def invited_to_sign_up?
       persisted? && invitation_token.present?
     end

       invitable.errors.add(:invitation_token, :invalid) if invitable.invitation_token && invitable.persisted? && !invitable.valid_invitation?

probably invited_to_sign_up? check on valid_invitation? was added later, so it's redundant. invited_to_sign_up checks the same it's checked on "if invitable.invitation_token && invitable.persisted?"

**Comment by scambra** [comment]
It's not redundat, you didn't understand the inline right because you removed invitation_period_valid?:

```ruby
invitable.errors.add(:invitation_token, :invalid) if invitable.invitation_token && invitable.persisted? && !(invitable.persisted? && invitable.invitation_token.present? && invitation_period_valid?)
```
it's the same as:
```ruby
invitable.errors.add(:invitation_token, :invalid) if invitable.invitation_token && invitable.persisted? && (!invitable.persisted? || !invitable.invitation_token.present? || !invitation_period_valid?)
```

So if invitable.invitation_token and invitable.persisted? are true, !invitable.persisted? and !invitable.invitation_token.present? are false, and the parenthesis is the same as !invitation_period_valid?, so it would be:
```ruby
invitable.errors.add(:invitation_token, :invalid) if invitable.invitation_token && invitable.persisted? &&  !invitation_period_valid?
```
Which sets invalid only for invited users with expired invitation. If it were only !valid_invitation?, like this:
```ruby
invitable.errors.add(:invitation_token, :invalid) if !valid_invitation?
```
It would set invalid for not invited users too. It wouldn't be wrong, becuase find_or_initialize_with_error_by(:invitation_token) will  return an invited user or a new user with :invalid error.

**Comment by jetaggart** [comment]
Ah, I see. Thanks for the explanation. Is the last line a simplification then?

**Comment by scambra** [comment]
Last line is a simplification, I think code could be changed to that without losing features, because it would set :invalid error on invitable with :invalid error already set, but I would have to test it

**Comment by arminnaimi** [comment]
Hi @scambra, thanks for your suggestion. After getting an empty array on:

    user.errors.to_a
   
Logs:
````
Started GET "/users/invitation/accept?invitation_token=x5RzixJQF5-uzWhp3HNG" for 127.0.0.1 at 2015-03-06 11:54:37 +0000
Processing by Devise::InvitationsController#edit as HTML
  Parameters: {"invitation_token"=>"x5RzixJQF5-uzWhp3HNG"}
  User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."invitation_token" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["invitation_token", "0dcae68bd50ba34d500d834deb29dacc5f0b861ac4670c0d05fa877fa8456868"]]
#<User id: 3, name: nil, email: "armin.naimi@gmail.com", encrypted_password: "", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, created_at: "2015-03-06 11:54:09", updated_at: "2015-03-06 11:54:09", organisation: nil, phone_number: nil, landline_number: nil, team: nil, title: nil, admin: false, account_id: nil, invitation_token: "x5RzixJQF5-uzWhp3HNG", invitation_created_at: "2015-03-06 11:54:09", invitation_sent_at: "2015-03-06 11:54:09", invitation_accepted_at: nil, invitation_limit: nil, invited_by_id: nil, invited_by_type: nil, invitations_count: 0>
[]
  Account Load (0.7ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."subdomain" = $1  ORDER BY "accounts"."id" ASC LIMIT 1  [["subdomain", "test"]]
  Account Load (1.4ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."subdomain" = $1 LIMIT 1  [["subdomain", "test"]]
  Status Load (1.5ms)  SELECT  "statuses".* FROM "statuses" WHERE "statuses"."statusable_id" = $1 AND "statuses"."statusable_type" = $2 LIMIT 1  [["statusable_id", 1], ["statusable_type", "Account"]]
  Rendered devise/invitations/edit.html.erb within layouts/devise (16.3ms)
Completed 200 OK in 92ms (Views: 70.2ms | ActiveRecord: 4.5ms)


Started PUT "/users/invitation" for 127.0.0.1 at 2015-03-06 11:55:24 +0000
Processing by Devise::InvitationsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"hP40kaGdECwzHxJlu4Z6O9GhTKLpq2lmmaFucLG3gI6M9anUBmoMzB719MjPzJM6XSuRPth2dhuGvfYh5zWaeA==", "user"=>{"invitation_token"=>"x5RzixJQF5-uzWhp3HNG", "title"=>"Mr", "name"=>"Armin Naimi", "organisation"=>"Test", "team"=>"Team", "phone_number"=>"07445188279", "landline_number"=>"07445188279", "email"=>"armin.naimi@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Create account"}
  Account Load (0.7ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."subdomain" = $1  ORDER BY "accounts"."id" ASC LIMIT 1  [["subdomain", "test"]]
  Account Load (1.0ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."subdomain" = $1 LIMIT 1  [["subdomain", "test"]]
  Status Load (0.4ms)  SELECT  "statuses".* FROM "statuses" WHERE "statuses"."statusable_id" = $1 AND "statuses"."statusable_type" = $2 LIMIT 1  [["statusable_id", 1], ["statusable_type", "Account"]]
  User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."account_id" = $1 AND "users"."invitation_token" = $2  ORDER BY "users"."id" ASC LIMIT 1  [["account_id", 1], ["invitation_token", "0dcae68bd50ba34d500d834deb29dacc5f0b861ac4670c0d05fa877fa8456868"]]
#<User id: nil, name: nil, email: "", encrypted_password: "", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, created_at: nil, updated_at: nil, organisation: nil, phone_number: nil, landline_number: nil, team: nil, title: nil, admin: false, account_id: 1, invitation_token: "x5RzixJQF5-uzWhp3HNG", invitation_created_at: nil, invitation_sent_at: nil, invitation_accepted_at: nil, invitation_limit: nil, invited_by_id: nil, invited_by_type: nil, invitations_count: 0>
["Invitation token is invalid"]
  Rendered devise/invitations/edit.html.erb within layouts/devise (10.2ms)
Completed 200 OK in 61ms (Views: 46.8ms | ActiveRecord: 2.8ms)
````
It looks like that only the invitation_token and account_id is filled, while the rest is set to nil. The invitation_token matches the params.

I am really confused.

**Comment by scambra** [comment]
To add some attributes in accept invitation form you have to allowed them in the controller, configuring devise_parameter_sanitizer. Read about it in README, strong parameters section.
