### ISSUE TITLE
Filter chain halted as :resource_from_invitation_token rendered or redirected

### ISSUE THREAD

**Issue by madhusudhan518** [scambra/devise_invitable#537]
When i sent a invitation to user
in my modal
Devise::Mailer.invitation_instructions(user, user.raw_invitation_token, {:domain => self.domain, :sub_domain => self.sub_domain})

In my mailer
<%= link_to I18n.t("devise.mailer.invitation_instructions.accept"), accept_user_invitation_url(::ActionMailer::Base.default_url_options.merge({:host =>@hub.sub_domain+'.'+@hub.core_domain_name, :invitation_token => @token})) %>
the above link giving url like this
"http://meetings.lvh.me:3000/users/invitation/accept?invitation_token=3DXuNoLrQLjNBnzqJp13AU"
when i click on the above link
the invitable controller process the above token like this

Started GET "/users/invitation/accept?invitation_token=3DXuNoLrQLjNBnzqJp13AU" for 127.0.0.1 at 2015-03-05 15:31:22 +0530
Processing by Users::InvitationsController#edit as HTML
  Parameters: {"invitation_token"=>"3DXuNoLrQLjNBnzqJp13AU"}
  User Load (0.2ms)  SELECT  "users".* FROM "users"  WHERE "users"."invitation_token" = '6bd8249e20e771e38afd0ff646df02e5c4f438cc5a4e7386f925047976359c26'  ORDER BY "users"."id" ASC LIMIT 1
Redirected to http://meetings.lvh.me:3000/
Filter chain halted as :resource_from_invitation_token rendered or redirected
Completed 302 Found in 4ms (ActiveRecord: 0.2ms)

the token stored in my DB is 
"8403602e98040871e3c5aa7e7a67941cc6e3ebda5c33f53043544ec10d2fad98"

i am using
Rails 4.1.6
devise 3.2.3
devise_invitable 1.3.5
InvitationsController::edit action is NOT overridden.
same like below
def resource_from_invitation_token
    unless params[:invitation_token] && self.resource = resource_class.find_by_invitation_token(params[:invitation_token], true)
      set_flash_message(:alert, :invitation_token_invalid) if is_flashing_format?
      redirect_to after_sign_out_path_for(resource_name)
    end
  end

can you tell me better way to find the error..

**Comment by isaacsloan** [comment]
Did you ever solve this? Same problem here.
