### ISSUE TITLE
active_for_authentication? change causes inconsistent results

### ISSUE THREAD

**Issue by mcbsys** [scambra/devise_invitable#541]
I'm using devise 3.4.1, devise_invitable 1.4.1, ruby 2.0.0, rails 3.2.16, rspec 2.14.1.

I'm having issues with update [96e9d33](https://github.com/scambra/devise_invitable/commit/96e9d3349437c99b15b6f81b1c3a0be3f343ecac) re. issue [503](https://github.com/scambra/devise_invitable/issues/503).

A. Tests that used to work with devise_invitable 1.3.4 now fail with this message:
````
An error occurred in an after hook
  ArgumentError: uncaught throw :warden
  occurred at /home/myuser/.rvm/gems/ruby-2.0.0-p598@myproject_rails3216/gems/devise-3.4.1/lib/devise/hooks/activatable.rb:8:in `throw'
````
I tracked this down to the behavior of the login_as helper. Before, it could sign in a user even with a pending invitation. The workaround is to first manually set a password and call `accept_invitation!`, then sign in. Not a big deal but I was surprised by the uncaught throw.

B. In development mode, I never see the new `inactive_message`, even after adding it to my custom config/locales/devise_invitable.en.yml file. (By default, the message reads, "You have a pending invitation, accept it to finish creating your account."). If an invitation is pending and I try to log in, I just get the normal "invalid email or password" message.

As best I can tell, this is because Devise first authenticates the username and password, _then_ checks `active_for_authentication?`. (See the comments in the Devise [source code](https://github.com/plataformatec/devise/blob/master/lib/devise/models/authenticatable.rb), "**After authenticating a user** and in each request, Devise checks if your model is active by calling model.active_for_authentication?.") When an invitation is pending, password validation will fail, so it doesn't get as far as calling `active_for_authentication?`. If you want to check a condition _before_ validating the password, you'll probably have to override `valid_password?` as devise_invitable did previously.

C. Most confusing to me is that in my features spec, the change _does_ work. The devise_invitable\model#active_for_authentication? method is called before the devise database_authenticatable#valid_password method, so I do see the new message in the test.  I have no explanation for why the sequence of calls is different between my test and development environments.

Is this all just me or do others see similar issues?  Are there tests to confirm that this works as expected?

[GitHub](http://github.com)

**Comment by scambra** [comment]
You are right, I have added a test for this case (sign in with invited user) and "invalid email or password" is displayed.

active_for_authentication is called in after_set_user warden callback, and it may be called only when password is valid (which is not possible in invited users unless password is set because you have changed behaviour to set password on invite).

So I will revert to override valid_password? as it did previously, and try to get a different message when trying to sign too.

**Comment by mcbsys** [comment]
Thanks for the quick solution!
