### ISSUE TITLE
Keep getting an Unauthorized when I try and pass the password for my User

### ISSUE THREAD

**Issue by SupremeA** [scambra/devise_invitable#544]
I am having an issue where I get the invitation to work and the User can accept it but when the user submits his pasword and confirms name it should login but instead I get an Unauthorized. Here is my log.

    Started POST "/tenants/invitation" for 10.0.2.2 at 2015-03-28 06:58:02 +0000
    Processing by Tenants::InvitationsController#create as HTML
      Parameters: {"utf8"=>"✓",     "authenticity_token"=>"AmwHWp2u1ZFm83mgurx6BGD8LrSJzYoKCD5fBgyTKjk=", "tenant"=>    {"invitation_token"=>"uC9LwXz4KB_B_b7MxvnB", "password"=>"[FILTERED]",     "password_confirmation"=>"[FILTERED]", "first_name"=>"John", "last_name"=>"Smith",     "ten_phone"=>"3332221212"}, "commit"=>"Complete Account Setup"}
    Completed 401 Unauthorized in 1ms

I am not sure where I am missing authorization in my application_controller I have the following:

      def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:first_name, :last_name, :avatar,  :avatar_cache, :zipcode, :company, :number_tenants, :man_phone, :ten_phone, :tenant_phone, :manager_phone) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name,  :zipcode, :company, :password, :password_confirmation, :email :man_phone, :ten_phone, :manager_phone) }
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :name, :email, :password, :password_confirmation, :avatar, :company, :ten_phone, :tenant_phone) }
        devise_parameter_sanitizer.for(:accept_invitation).concat [:invitation_token, :password, :password_confirmation, :first_name, :last_name, :ten_phone, :zipcode, :state, :current_streetname, :current_city]
        devise_parameter_sanitizer.for(:accept_invitation) do |u|
          u.permit(:first_name, :last_name, :ten_phone, :password, :password_confirmation,
               :invitation_token)
        end

Unsure of anywhere else I need to authorize, here is the form for password:
     <%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :post } do |f| %>

One last thing, I can see the user/tenant in my console:

     => #<Tenant _id: 5516442f7261693861100000, avatar: nil, invited_by_type: "Manager", invited_by_id: BSON::ObjectId('551643f772616955930a0000'), email: "sample@gmail.com", encrypted_password: "", first_name: "John", last_name: "Smith", zipcode: nil, ten_phone: "3332221212", invitation_token: "8e6a6a704de9eb05b1370799fbd3880ad743ec5e3383c6e97b66d20d449ae884", invitation_created_at: 2015-03-28 06:03:27 UTC, invitation_sent_at: nil, invitation_accepted_at: nil, invitation_limit: nil, reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, confirmation_token: nil, confirmed_at: nil, confirmation_sent_at: nil, unconfirmed_email: nil>

**Comment by scambra** [comment]
You must set :method => :put, :method => :post invokes create action instead of update action, which is accept invitation action

**Comment by SupremeA** [comment]
I changed this :method => :put but I still don't get it to login the User. Let me ask you this where does this go in the controller or model. 

    User.accept_invitation!(:invitation_token => params[:invitation_token], :password => self.password, :name => "self.user_name")

Also, I get it to go to the edit page and ask for a password but when I put it in it takes me to the update page next and it does not save the password, I cant figure out why, I want it to go to the password page and after the password automatically log the user in. I would redirect in the controller after the password but for some reason it wont save the password.

Can you tell me what Im missing?

**Comment by scambra** [comment]
You don't need to call User.accept_invitation!, invitations controller do that. Can you post log on accepting invitation with :method => :put? Anyway, it can be failing because you didn't pass :password_confirmation (by default is needed in devise, if you didn't change any validations)

**Comment by SupremeA** [comment]
Ok so here is the log when a User clicks the unique email link...

    Started GET "/tenants/invitation/accept?invitation_token=R9rUDSSiHhF6tkX-xLRq" for 10.0.2.2 at 2015-03-31 13:02:49 +0000
    Processing by Tenants::InvitationsController#edit as HTML
      Parameters: {"invitation_token"=>"R9rUDSSiHhF6tkX-xLRq"}
    D, [2015-03-31T13:02:50.401041 #20546] DEBUG -- :   MOPED: 127.0.0.1:27017 QUERY         database=lease_defend_development collection=tenants selector={"$query"=> {"invitation_token"=>"5d445c14d70c93ad49a33f16154bff118b82e5d60821f336b65de6b630289745"},  "$orderby"=>{:_id=>1}} flags=[] limit=-1 skip=0 batch_size=nil fields=nil runtime: 0.6123ms
      Rendered tenants/invitations/_password_step.html.erb (2.6ms)
      Rendered tenants/invitations/_confirm_name_step.html.erb (5.2ms)
      Rendered tenants/invitations/edit.html.erb within layouts/application (54.2ms)
    Completed 200 OK in 263ms (Views: 259.4ms)

And here is the spot I'm having trouble with. After the user inputs password and confirms name then it should create the account and log user in but on the log I get this...

    Started PUT "/tenants/invitation" for 10.0.2.2 at 2015-03-31 13:06:15 +0000
    Processing by Tenants::InvitationsController#update as HTML
      Parameters: {"utf8"=>"✓",  "authenticity_token"=>"l4GKhfgxuQbADllUoI3hIUYOs81Wmt/+LkVzxqhNPeU=", "tenant"=>{"invitation_token"=>"R9rUDSSiHhF6tkX-xLRq", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Aisha", "last_name"=>"Tester", "ten_phone"=>"6547689865"}, "commit"=>"Complete Account Setup"}
      Rendered tenants/invitations/update.html.erb within layouts/application (0.4ms)
    Completed 200 OK in 218ms (Views: 217.3ms)

This is the view of the edit invitations page

    <%= form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :put }) do |f| %>
      <%= devise_error_messages! %>
      <%= f.hidden_field :invitation_token %>
    <br />
    <%= render partial: "password_step", locals: {tenant: @tenant}, :locals => {:f => f} %>

    <%= render partial: "confirm_name_step", locals: {tenant: @tenant}, :locals => {:f => f} %>

    <br />
    <div class="form-group">
      <%= f.submit "Complete Account Setup", class: 'btn btn-success' %>
    </div>
    <% end %>

Thanks for your help,I really appreciate it, please let me know if you need to see anything else to help me fix this.

**Comment by scambra** [comment]
Is it running on production mode? Can you run on development or enable debug so SQL queries are logged?

**Comment by scambra** [comment]
update action in default invitations controller doesn't render update view, it renders edit if accept fails and redirect if update works, so post your update action if you have overrided it

**Comment by SupremeA** [comment]
My invitations_controller

    class Tenants::InvitationsController < Devise::InvitationsController

      def edit
      end

      def update
      end

      def sign_up
        default_params.permit(:first_name, :last_name, :ten_phone, :invitation_token, :password, :password_confirmation)
      end

      def authorization_params
        params.permit(:first_name, :last_name, :ten_phone, :invitation_token, :password,   :password_confirmation)
      end

    end

**Comment by scambra** [comment]
You should remove def edit and def update, no code it's being executed on these actions because you overrided them

**Comment by SupremeA** [comment]
Ok removed edit & update but it did the same thing, did not pass the password and went from edit page to update page. here is the log when clicking the link...

    Started GET "/tenants/invitation/accept?invitation_token=7m3T4ScqKruiV1bLgJSz" for 10.0.2.2 at 2015-03-31 13:36:27 +0000
    Processing by Tenants::InvitationsController#edit as HTML
      Parameters: {"invitation_token"=>"7m3T4ScqKruiV1bLgJSz"}
    D, [2015-03-31T13:36:27.824312 #20546] DEBUG -- :   MOPED: 127.0.0.1:27017 QUERY        database=lease_defend_development collection=tenants selector={"$query"=>{"invitation_token"=>"abfe74672d01572500f57542c05e7d5b27c575a236130be9deaf294b1b30fd24"}, "$orderby"=>{:_id=>1}} flags=[] limit=-1 skip=0 batch_size=nil fields=nil runtime: 0.6017ms
      Rendered tenants/invitations/_password_step.html.erb (1.9ms)
      Rendered tenants/invitations/_confirm_name_step.html.erb (1.6ms)
      Rendered tenants/invitations/edit.html.erb within layouts/application (47.7ms)
    Completed 200 OK in 269ms (Views: 265.4ms)

Here is the log after inputing the password...

    Started PUT "/tenants/invitation" for 10.0.2.2 at 2015-03-31 13:36:54 +0000
    Processing by Tenants::InvitationsController#update as HTML
      Parameters: {"utf8"=>"✓",  "authenticity_token"=>"k+P8CfkT+ywcLPhplxI5Tlr4dhaawdEvTaZF9QqUlj8=", "tenant"=>{"invitation_token"=>"7m3T4ScqKruiV1bLgJSz", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "first_name"=>"Aisha", "last_name"=>"ThinsMeGotIt", "ten_phone"=>"3271282387"}, "commit"=>"Complete Account Setup"}
      Rendered tenants/invitations/update.html.erb within layouts/application (0.1ms)
    Completed 200 OK in 225ms (Views: 224.3ms)

**Comment by scambra** [comment]
Is it running on production mode? Can you run on development or enable debug so SQL queries are logged?

**Comment by SupremeA** [comment]
Its running in development mode and from what I see debug is enabled...

    module Project
      class Application < Rails::Application
        Mongoid.logger.level = Logger::DEBUG
        Moped.logger.level = Logger::DEBUG
        # Settings in config/environments/* take precedence over those specified here.
        # Application configuration should go into files in config/initializers
        # -- all .rb files in that directory are automatically loaded.
    
        # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
        # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
        # config.time_zone = 'Central Time (US & Canada)'
    
        # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
        # config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
        # config.i18n.default_locale = :de
      end
    end

**Comment by scambra** [comment]
Then something wrong is going on your Tenants::InvitationsController, because update it's doing no SQL query

**Comment by SupremeA** [comment]
Should I delete that controller entirely and let it run off of the devise default controller? Only thing is I have another user type(manager) so I don't know if that will cause an issue not having a separate controller?

**Comment by scambra** [comment]
You only need separate controllers if you have to do something different for each resource, but it should work if you don't remove code from devise invitable (as defining an empty update action). I see edit action works now, becuase it looks for resource using invitation token, but no query is done on update.

Also, where is authorization_params used?

**Comment by SupremeA** [comment]
The only thing I need to do different concerning user types and invitations is to send them to their own respective dashboard type.

i.e. managers go to manager dashboard instance upon account creation
and tenants go to tenants dashboard instance upon account creation

Thats it so I thought with that I WOULD need a separate controller for that.

And the authorization_params really was just to get the parameters to be passed to the database (mongodb) but really I have the params permits in the application controller so they are unnecessary. I just haven't cleaned them up until I got this invitation to work.

**Comment by SupremeA** [comment]
Hey Thanks so much for your help I got it! The issue was I created a partial for edit and update to be on the same page and that caused an issue because the edit needed the put method while the update method needed the patch method! Thanks again for your help. 

Now I will tell all my friends to ask you about their devise_inviable issues directly! LOL Just kidding! Thanks again for your help!
