### ISSUE TITLE
[question] Invite users without creating a new user until the invitation is accepted OR differentiate between users registering traditional way and the invitations

### ISSUE THREAD

**Issue by famousky** [scambra/devise_invitable#546]
I want to keep traditional sign up page and let the user register through it but on the top of it, in his profile he will be able to refer/invite new members.

I am trying to find out how to tell devise invitable to NOT create new user in database yet, just store a record and wait with creation until the user come to the site from the token and set password.

OR at least to differentiate the users who register through the invites and those who register through traditional way so I can trigger welcome email to only those who registered traditional way and for those who are invited, until they set their password and log first time into account.

**Comment by scambra** [comment]
Not possible to skip user creation when inviting, there is a request for it but it's a big change and I don't have time for it.

You can differentiate if user is invited or registered checking invited_by for example. Also, you can differentiate registered user and invited user without accepting invitation with method invited_to_sign_up?

**Comment by famousky** [comment]
@scambra thank you - I will use method *invited_to_sign_up?*.
Regarding the way to check is the user who is invited already accepted invitation, is there a way to use a method similar to that callback *after_invitation_accepted* ?
I found this callback very useful so I can trigger welcome email only if *after_invitation_accepted* and not on *after_create* callback like I did before!

**Comment by scambra** [comment]
```ruby
class User < ActiveRecord::Base
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :perform_tasks_for_new_user, :unless => :invited_to_sign_up?
  after_invitation_accepted :perform_tasks_for_new_user

#########
##### bunch of my other code here
########

  private
  def perform_tasks_for_new_user
    UserMailer.welcome_email(self).deliver_later
    SubscribeUserToMailingListJob.perform_later(self)
  end

end
```

**Comment by famousky** [comment]
@scambra nice, I did not know you can pass **unless** up there! Learned something new :) Thank you!

**Comment by laetitiamassa** [comment]
Hi there,

Great gem :), thanks !

I'm not sure I understand the solution here, but I'm trying to do something similar:
- when a user who has already been invited but hasn't accepted the invitation yet tries to create an account (via registration controller create action - devise), it is redirected to registration controller new, with the message "email is not available".

How to use invited_to_sign_up? in order to allow that user to simply enter the app without having to go find his invitation mail ?

(i'll post the question as a new one if necessary).

Many thanks in advance!

**Comment by scambra** [comment]
@laetitiamassa It should work.

Are you using lastest devise_invitable (1.5.3)? A bug related to registration was fixed on that version.

Are you overriding registrations controller? In that case, you should inherit from DeviseInvitable::RegistrationsController
