### ISSUE TITLE
Turn off invitation creation routes

### ISSUE THREAD

**Issue by toobulkeh** [scambra/devise_invitable#550]
I'm currently writing a system with 3 separate user types/tables. These roles allow type1 to invite types1,2,3 and type2 to invite types2,3.

I'd like for them all to be able to accept invites still, but I've created separate invite actions / controllers to limit everything down, so I'd like to turn off the default routes for creating invitations on `devise_for :patients`

Any ideas how to turn off creating invitations there but still allowing invitations to be accepted?

Thanks!

**Comment by scambra** [comment]
Probably you will have to add invitations routes by yourself, using:

```ruby
devise_scope :patient do
  get :edit, :path => 'accept', :as => :accept
  put :update
  get :destroy, :path => 'remove', :as => :remove
end

**Comment by toobulkeh** [comment]
I was afraid of that. Thanks for the tips.

**Comment by toobulkeh** [comment]
For some reason Rails didn't like that pathing information, so I ended up with this verbose nastyness:
```Ruby
get 'patients/invitation/accept', to: 'devise/invitations#edit', as: :accept_patient_invitation
put 'patients/invitation', to: 'devise/invitations#update', as: :update_patient_invitation
get 'patients/invitation/remove', to: 'devise/invitations#destroy', as: :remove_patient_invitation
```

**Comment by scambra** [comment]
Maybe path is only valid inside a resources block, I guess devise_for process path or use a resources block.

**Comment by fredkelly** [comment]
I'm trying to achieve something similar, I know that I can add the routes manually as described above, but how do I then disable the invitation routes that are created by default?

**Comment by toobulkeh** [comment]
@fredkelly I believe it's the same way as turning off devise paths:

```ruby
devise_for :users, :skip => [:registrations] 
```

**Comment by fredkelly** [comment]
Perfect, thanks Dan!
