### ISSUE TITLE
Unable to override after_invite_path_for(resource) in ApplicationsController

### ISSUE THREAD

**Issue by Yanchek99** [scambra/devise_invitable#559]
I have defined the following method in my Application Controller.  I also would like to mention that I do not have any custom controllers for devise or devise_invitable.  I am currently running Rails 4.2 with Devise 3.4.1 and devise_invitable 1.4.2 (checked to make sure overrides were supported).  Perhaps @mwear  can provide some support?

```
def after_invite_path_for(resource)
    root_path
end
```

However when I invite a new member, I am not redirected to the correct path.

**Comment by marcamillion** [comment]
@Yanchek99 What was the issue with this? Did it ever work for you?
