### ISSUE TITLE
devise_invitable relies on after_password_reset callback that is deprecated in Devise 3.5.1

### ISSUE THREAD

**Issue by tony-f** [scambra/devise_invitable#562]
In Devise 3.5.1, the ```after_password_reset``` callback is deprecated (see devise commit plataformatec/devise@31901bc862db60878130fcd9cbf9c4895d41b2d2).  There does not seem to be a replacement callback, at least upon initial review.

devise_invitable relies on the ```after_password_reset``` callback currently in ```lib/devise_invitable/model.rb``` which leads to deprecation warnings when using devise_invitable.

```DEPRECATION WARNING: after_password_reset is deprecated.```

devise_invitable will need to rely on another mechanism to do what it needs to without relying the on the deprecated devise ```after_password_reset``` callback.

**Comment by scambra** [comment]
Probably a before_update could be used, as this change does for clear_reset_password_token
https://github.com/plataformatec/devise/commit/31901bc862db60878130fcd9cbf9c4895d41b2d2

**Comment by tony-f** [comment]
Just tried master that included the fix and worked great for me.  Thanks a bunch @scambra !
