### ISSUE TITLE
find_by_invitation_token sets invitation_token to raw token

### ISSUE THREAD

**Issue by afn** [scambra/devise_invitable#564]
The `find_by_invitation_token` changes the `invitation_token` attribute of the returned object to the plaintext token:

```ruby
def find_by_invitation_token(original_token, only_valid)
  invitation_token = Devise.token_generator.digest(self, :invitation_token, original_token)

  invitable = find_or_initialize_with_error_by(:invitation_token, invitation_token)
  invitable.errors.add(:invitation_token, :invalid) if invitable.invitation_token && invitable.persisted? && !invitable.valid_invitation?
  invitable.invitation_token = original_token # <--- HERE
  invitable unless only_valid && invitable.errors.present?
end
```

There's no explanation of why this is done, but I suspect it's because we wanted to maintain backwards compatibility with custom accept-invitation views when token encryption was added in 90634f10eb0adb4b3f47171010c51014345a26ef.

Doing this in the model is pretty busted, though, because one would expect to be able to call `find_by_invitation_token` without dirtying the user.  For instance, this:

```ruby
return unless user = find_by_invitation_token(params[:token], true)
user.update! some_field: 'some_value'
```

will cause the user's `invitation_token` (rather surprisingly) to be updated in the database to the raw token, which can no longer be used to authenticate him.

I'll submit a PR shortly to fix this issue by moving the code that sets `invitation_token` to the raw token into `InvitationsController`, so that it's only ever done when the resource is being rendered in a view.

**Comment by scambra** [comment]
fixed on #565
