### ISSUE TITLE
Invited users with a password can sign in since devise 3.5.1

### ISSUE THREAD

**Issue by noxmad** [scambra/devise_invitable#571]
In devise 3.5.1, clear_reset_password_token is called in a before_update callback (see https://github.com/plataformatec/devise/commit/31901bc862db60878130fcd9cbf9c4895d41b2d2).

Moving from using after_password_reset to using clear_reset_password_token in 848de10a has inadvertently allowed invited users to sign in if their password is set (without having to go through the reset password procedure or accepting an invite). This in turn breaks the invitation test 'invited user with password should not be able to sign in'.

Even though it is not that likely that people will be setting the password and saving the resource after inviting a user (and outside of a user requested password reset), it is unexpected behaviour.

**Comment by scambra** [comment]
I don't think there is a way to set password for an invited user, which has no password, to set password without going through the reset password procedure or accepting an invite. So I think that test doesn't make sense

**Comment by noxmad** [comment]
In most cases yes it is unlikely for the password to be set without going through normal devise procedures but that doesn't stop people from addind their own custom logic during the invitation that changes the password. An example of this would be issue #531 where we may want to set the password to something random before or during the invitation.

In my opinion the only way to accept an invite should be by clicking the accept invitation link, but I assume that allowing invitation acceptance via password resetting is allowed because to do that the customer must check their email?

**Comment by scambra** [comment]
Yes, if you are invited and reset password, you are using link from email, so it's allowed. Also, it would be weird to allow start reset password procedure but not accept user.
