### ISSUE TITLE
User Autoconfirmed in 1.5.1 on update_attributes

### ISSUE THREAD

**Issue by bublik** [scambra/devise_invitable#578]
>   VERSION = '1.5.0'

 expect(invited_email_user.invitation_accepted_at).to be_blank
   invited_email_user.update_attributes({email: 'test@ff.com'})
   invited_email_user.reload
   expect(invited_email_user.invitation_accepted_at).to be_blank  # SUCCESS

>   VERSION = '1.5.1'

 expect(invited_email_user.invitation_accepted_at).to be_blank
   invited_email_user.update_attributes({email: 'test@ff.com'})
   invited_email_user.reload
   expect(invited_email_user.invitation_accepted_at).to be_blank  # FAIL

**Comment by scambra** [comment]
it was fixed on #571, you should try with 1.5.2

**Comment by bublik** [comment]
Could not find gem 'devise_invitable (= 1.5.2) ruby' in any of the gem sources listed in your Gemfile or installed on this machine.
https://rubygems.org/gems/devise_invitable
Last version
1.5.1 - June 16, 2015 (40 KB)

**Comment by biow0lf** [comment]
@bublik 1.5.2 doesn't released yet. Now, this is master branch.

Try replace ```gem 'devise_invitable'``` in ```Gemfile``` with ```gem 'devise_invitable', github: 'scambra/devise_invitable'```.

**Comment by scambra** [comment]
My bad, I had gem ready but not pushed, you can install now
