### ISSUE TITLE
generate not work

### ISSUE THREAD

**Issue by TangMonk** [scambra/devise_invitable#579]
typing following command:

```
rails generate devise_invitable:install
```

it show me:

```
Could not find generator 'devise_invitable:install'. Maybe you meant 'devise:install', 'ckeditor:install' or 'rails_admin:install'
```

I use 1.5.2

**Comment by TangMonk** [comment]
sorry, maybe `zeus` problem, I restart my mac, it works

**Comment by spchetan11** [comment]
Yeah. Restarting worked for me too. weird.

**Comment by nezirz** [comment]
I tried with restarting and not worked in my case ruby 2.5.1 rails 5.2.3 dell xps ubuntu 18.04.
What worked is:

`bundle exec gem install devise_invitable`

then I saw that it installed version:

```
Successfully installed devise_invitable-2.0.1
Parsing documentation for devise_invitable-2.0.1
Done installing documentation for devise_invitable after 0 seconds
1 gem installed 
```

so I updated Gemfile line to correct version:
`gem 'devise_invitable', '~> 2.0.1'`

and then run `rails generate devise_invitable user `successfully!
