### ISSUE TITLE
Wrong encrypted token generation

### ISSUE THREAD

**Issue by Chambeur** [scambra/devise_invitable#580]
I'm using :
* Ruby 2.2
* Rails 4.2
* Devise 3.5.1
* Devise_invitable 1.5.2 (same issue with 1.3.5)

#### Use case
An admin user is sending invitation to an agency user.
I'm using a custom view to display the email with this link:
`accept_invitation_url(@resource, invitation_token: @token)`

#### Issue
When I click on email link, I have the error: _The invitation token provided is not valid!_

I tested in Rails console some things:
Token from the email: 3Drz1qJg8PCn5v2oeC7XuU

AgencyUser.find_by_invitation_token("3Drz1qJg8PCn5v2oeC7XuU", false)
`=> #<AgencyUser id: nil, agency_id: nil, first_name: nil, last_name: nil, email: "", encrypted_password: "", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, created_at: nil, updated_at: nil, invitation_token: "bdd8cec81b8094efb66406e22243d9977de698ee3c935580b0...", invitation_created_at: nil, invitation_sent_at: nil, invitation_accepted_at: nil, invitation_limit: nil, invited_by_id: nil, invited_by_type: nil>`

Devise.token_generator.digest(AgencyUser, :invitation_token, "3Drz1qJg8PCn5v2oeC7XuU")
 `=> "bdd8cec81b8094efb66406e22243d9977de698ee3c935580b04cfcb9ea2a2a9d"`

AgencyUser.all
`=> #<ActiveRecord::Relation [#<AgencyUser id: 1, agency_id: 1, first_name: "Lorem", last_name: "Ipsum", email: "lorem@test.com", encrypted_password: "$2a$10$Wb7SkdfEV.CVT2Jh/mDcM.vD6aL.CpqDg3BXno23O/Y...", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, created_at: "2015-07-24 08:38:57", updated_at: "2015-07-24 08:38:57", invitation_token: "c6f096c81c74c15480f71c4972245bf58fedfb1714fba398af...", invitation_created_at: "2015-07-24 08:38:57", invitation_sent_at: "2015-07-24 08:38:57", invitation_accepted_at: nil, invitation_limit: nil, invited_by_id: nil, invited_by_type: nil>]>`

###### tl;dr
token in db: `c6f096c81c74c15480f71c4972245bf58fedfb1714fba398af6b5e447cccddb7`
token check generated: `bdd8cec81b8094efb66406e22243d9977de698ee3c935580b04cfcb9ea2a2a9d`

It looks like the token is not generate in the same way when the AgencyUser is created.

**Comment by scambra** [comment]
Can you send insert agency user sql?

**Comment by Chambeur** [comment]
### New test

Token from email: `3DWb9QdUhwjhqqT7aKGJ4s`
Token check generated: `74a337e2309ef5e7566ec4251f1947b8018875d106ee1f5490dd2835da7fad8b`
Token in db: `063a01cedfb4a13b15f5d9339191b93bd1df165b3f3dd4114009e1e266342b91`

    INSERT INTO "agency_users" ("email", "first_name", "last_name", "agency_id", "encrypted_password", "invitation_token", "invitation_created_at", "invitation_sent_at", "created_at", "updated_at") 
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) 
    RETURNING "id"  [
        ["email", "john@doe.com"], 
        ["first_name", "John"], 
        ["last_name", "Doe"], 
        ["agency_id", 1], 
        ["encrypted_password", "$2a$10$n7iZJXKS047ryehfVL67hOiYo2ISIDRVEAuX4Zuq56Yhj3xQu81xa"], 
        ["invitation_token", "063a01cedfb4a13b15f5d9339191b93bd1df165b3f3dd4114009e1e266342b91"], 
        ["invitation_created_at", "2015-07-30 06:27:27.830700"], 
        ["invitation_sent_at", "2015-07-30 06:27:27.830700"], 
        ["created_at", "2015-07-30 06:27:27.832301"], 
        ["updated_at", "2015-07-30 06:27:27.832301"]
    ]

**Comment by scambra** [comment]
Is it happenning with other devise tokens, like confirmation token?

Also you can test token generator in console:

```ruby
raw, enc = Devise.token_generator.generate(AgencyUser, :invitation_token)
puts raw
puts enc
digest = Devise.token_generator.digest(AgencyUser, :invitation_token, raw)
puts digest
enc == digest
```

**Comment by Chambeur** [comment]
I've found my issue, it's due to quoted-printable encoding in the emails. The characters `3D` was added after the equal sign (just before the token).

However, it does work with the reset_password_token. The Devise Mailer send the email with this encoding:

    Mime-Version: 1.0
    Content-Type: text/html;
     charset=UTF-8
    Content-Transfer-Encoding: 7bit

And the Devise Invitable Mailer send the email with this encoding:

    Mime-Version: 1.0
    Content-Type: text/html;
     charset=UTF-8
    Content-Transfer-Encoding: quoted-printable

How can I set the same Content-Transfer-Encoding to 7-bit for Devise Mailer and Devise Invitable Mailer ?

**Comment by scambra** [comment]
I don't know, ActionMailer probably is setting different encoding depending on content. DeviseInvitable uses Devise mailer, only adds a method to send new mail with own views. However enconding should not be an issue, it's an html email, so if you view as HTML, you shouldn't view these 3D encoding characters (most probably =3D)

**Comment by franckdelage** [comment]
A year and a half later, thank you @Chambeur, for the `3D` characters, you saved my day !
