### ISSUE TITLE
README uses old versions of devise-invitable

### ISSUE THREAD

**Issue by laurelfan** [scambra/devise_invitable#587]
````
gem 'devise',           '>= 2.0.0'
gem 'devise_invitable', '~> 1.3.4'
````

The README file lists old versions of devise_invitable and devise. Is there a reason for this or should the README be updated with the latest stable versions?

**Comment by smcabrera** [comment]
Elsewhere in the documentation it says something about being updated to work with the latest version of devise so I suspect that's an oversight and should be updated.
