### ISSUE TITLE
How to skip the pending invitations control when login in

### ISSUE THREAD

**Issue by marcocanderle** [scambra/devise_invitable#590]
I have a Rails/Mongoid application using devise and devise_invitable gems with a special scenario where a User has_and_belongs_to_many groups. This in the application means that a User can be invited to one or more groups by other users. I'm using devise_invitable to handle those invites for both new and existing users.

The scenario where I'm having problems is when a user that has already registered and confirmed its account, and that might have already be invited to one group, is invited to another group. In this case the system sends the new invitation as usual but for the existing User instead of creating a new one to be invited.

If the user confirms the invitation everything works ok, but the problem I'm having is that unless the user confirms it, he/she won't be able to login again into his user account because it will get the alert:

    You have a pending invitation, accept it to finish creating your account.

So I'm wondering how should I do or what should I override on Devise/Devise_invitable in order to skip that control when trying to login as a user that has already been confirmed but has a pending invitation.

My User model is this one:

    class User
      include Mongoid::Document
      include Mongoid::Attributes::Dynamic
      include Mongoid::Timestamps
      include Mongoid::Userstamp::User

      devise :invitable, :encryptable, :database_authenticatable, :registerable, :lockable, :recoverable, :confirmable, :rememberable, :trackable, :validatable, :timeoutable

      has_and_belongs_to_many :groups

Thanks!

**Comment by scambra** [comment]
You can override block_from_invitation? method, current code is:

```ruby
        def block_from_invitation?
          invited_to_sign_up?
        end

**Comment by marcocanderle** [comment]
Great.

Thanks for your quick help!

**Comment by nfedyashev** [comment]
@scambra 
maybe you can share a simple way to do that without forking devise_invitable? Adding it to User model doesn't help.
Thanks

**Comment by scambra** [comment]
You should add that method to your model, below devise line. For example:

```ruby
def block_from_invitation?
  false
end
```

@nfedyashev you must be doing something wrong, because it's working for @marcocanderle

**Comment by marcocanderle** [comment]
@nfedyashev This is what I did on my User model:

    class User
      include Mongoid::Document
      include Mongoid::Attributes::Dynamic
      include Mongoid::Timestamps
      include Mongoid::Userstamp::User

      devise :invitable, :encryptable, :database_authenticatable, :registerable, :lockable, :recoverable, :confirmable, :rememberable, :trackable, :validatable, :timeoutable

      has_and_belongs_to_many :groups

      def block_from_invitation?
        # If the user has not been confirmed yet, we let the usual controls work
        if confirmed_at.blank?
           return invited_to_sign_up?
        else # if the user was confirmed, we let them in (will decide to accept or decline invitation from the dashboard)
           return false
        end
      end

**Comment by nfedyashev** [comment]
@scambra @marcocanderle thanks!
The reason why it didn't work for me was the old 1.4.0 version that I was using.

**Comment by IamNaN** [comment]
For people googling into this issue, you might need `invitation_accepted_at.blank?` instead of `confirmed_at `.
