### ISSUE TITLE
password_confirmation ignored when accepting invitation

### ISSUE THREAD

**Issue by imackinn** [scambra/devise_invitable#592]
When accepting an invitation through an email link, `password` will accept a password, however, if it does not match `password_confirmation`, the password is still set without any validation errors.

**Comment by scambra** [comment]
that's weird, there is a test for accepting with invalid password confirmation, and it's passing
https://github.com/scambra/devise_invitable/blob/master/test/models/invitable_test.rb#L199

**Comment by mkhairi** [comment]
hi @scambra,  i got similar issue. but different situation. i'm using normal registration, then sign up again using same email again will allow to login directly even password and password confirmation leave blank!  seems like email, password validation is skipped. if i remove this gem, everything just work normal.

**Comment by scambra** [comment]
@mkhairi I'm not sure I follow you.

Is it this case?
1. invite user with email A
2. sign up with email A
3. sign up with email A again, then got logged in

Or this case?
1. sign up with email A
2. sign up with email A again, then got logged in

**Comment by mkhairi** [comment]
@scambra 

1. sign up with email A
2. sign up with email A again, then got logged in

**Comment by scambra** [comment]
I have tried to add some test case but not fails, I would need a sample app to reproduce the issue

**Comment by mkhairi** [comment]
@scambra  here the sample app [gemologists.herokuapp.com](http://gemologists.herokuapp.com)

**Comment by scambra** [comment]
with sample app I mean code of a small app to reproduce it and debug it

**Comment by mkhairi** [comment]
https://github.com/mkhairi/gemologists

**Comment by scambra** [comment]
@imackinn, are you using :validatable? or added custom validations?

**Comment by scambra** [comment]
@mkhairi fixed with acfe692, thanks

**Comment by mkhairi** [comment]
:+1:

**Comment by imackinn** [comment]
@scambra

**Comment by imackinn** [comment]
@scambra 

```
  validates_uniqueness_of :email, allow_blank: true, if: :email_changed?
  validates_format_of     :email, with: Devise.email_regexp, allow_blank: true, if: :email_changed?
  validates_inclusion_of :time_zone, in: ActiveSupport::TimeZone.zones_map(&:name).keys, allow_blank: true
  validates :account, presence: true
  validates :password, length: { minimum: 6 }, allow_nil: true  
```

**Comment by scambra** [comment]
You don't have a confirmation validation for password, invitable doesn't worry about validations of devise fields, they are usually managed with :validatable or by custom validations

**Comment by jennykortina** [comment]
Hi @scambra,

I'm having the same issue @imackinn had.  When a user accepts the invite and is redirected to /users/invitation/accept if they enter a non-valid password no errors are thrown and they are just redirected to /users/invitation/accept.  How do I throw validation errors?  Here's a gist of my controller:

https://gist.github.com/jennykortina/6d4ad5633ee7dac9c3ca339f9cb06ec4

Thanks!

**Comment by jennykortina** [comment]
@scambra also i don't have :validate_on_invite => true turned on.  if i turn it on when i try to accept an invite i get "invalid token error" if i don't have :validate_on_invite => true i do not get an invalid token error.  i'm using custom mailers you can see here:

https://gist.github.com/jennykortina/d7351b92ca7daac14e2b2c515a0a79b6

https://gist.github.com/jennykortina/39ab2f4cff4655242b0a4a24064ffeee

thanks!

**Comment by jennykortina** [comment]
@scambra I figured it out.  Thanks :)
