### ISSUE TITLE
Question: Passing subdomain in accept_invitation_url

### ISSUE THREAD

**Issue by ashwinputhige** [scambra/devise_invitable#600]
I noticed that with devise-async, the Accept Invitation link did not contain the subdomain. So, I added subdomain to ```accept_invitation_url``` and it worked. Could you please tell me if it is the correct way to do it?

```
<p><%= link_to t("devise.mailer.invitation_instructions.accept"), accept_invitation_url(@resource, :invitation_token => @token, :subdomain => @resource.subdomain) %></p>
```

**Comment by scambra** [comment]
that's right
