### ISSUE TITLE
Sending both confirmable and invitable emails

### ISSUE THREAD

**Issue by ssnake** [scambra/devise_invitable#601]
Happening to me with:
devise (3.5.2)
devise_invitable (1.5.3)

my model:
```ruby
class User < ActiveRecord::Base
...
  devise :invitable, :database_authenticatable, :registerable, :confirmable, 
         :recoverable, :rememberable, :trackable, :validatable
...
end
```

my controller method:

```ruby
  def send_invitation
    @record = User.new email: params[:email]
    @record.company = current_company
    
    
    if @record.invalid?
      @errors = @record.errors 
      @errors.delete(:password) #ignore password absence
    else
      @errors = {}
    end


    @record.save!(validate: false) if  @errors.empty?
    
    @record.invite! if @errors.empty?
    
    respond_to do |format|
        format.js {}
    end
  end
```

confirmation_instructions is fired first, then invitation_instructions

**Comment by scambra** [comment]
You shouldn't save before invite, because save will fire sending confirmation, and then invite! will disable sending confirmation, but confirmation email is already sent. Also, invite! already calls save.

Anyway, you can use invite! class method, instead of long code:
```ruby
record = User.invite!(email: params[:email]) do |record|
  record.company = current_company
end
@errors = @record.errors

**Comment by ssnake** [comment]
Thanks. This solved my issue.

**Comment by ziaulrehman40** [comment]
Doesn't this invite! method skip validation?
It says so in readme.

**Comment by scambra** [comment]
invite! class method (User.invite!) skip validations, unless validate_on_invite is enabled
