### ISSUE TITLE
Call `set_minimum_password_length` on edit action

### ISSUE THREAD

**Issue by MarkMurphy** [scambra/devise_invitable#605]
[invitations_controller.rb#L33-L36](https://github.com/scambra/devise_invitable/blob/master/app/controllers/devise/invitations_controller.rb#L33-L36)

Should look more like this:

```ruby
def edit
  set_minimum_password_length
  resource.invitation_token = params[:invitation_token]
  render :edit
end
```

See [registrations_controller.rb#L8](https://github.com/plataformatec/devise/blob/7df57d5081f9884849ca15e4fde179ef164a575f/app/controllers/devise/registrations_controller.rb#L8) and [devise_controller.rb#L157-L162](https://github.com/plataformatec/devise/blob/7df57d5081f9884849ca15e4fde179ef164a575f/app/controllers/devise_controller.rb#L157-L162)

**Comment by scambra** [comment]
I suppose it can be added with a respond_to? so it works with previous versions

**Comment by scambra** [comment]
Fixed on 66b6075, I forgot to write comment

**Comment by cbisnett** [comment]
I was just looking at this and `respond_to?` returns false even though the method exists because it's private. You can fix this by adding the second optional parameter like this `respond_to? :set_minimum_password_length, true`

**Comment by scambra** [comment]
thanks, you are right, it only worked in old ruby versions. It's not needed anymore because version without this method is not supported
