### ISSUE TITLE
creating an invite from a different user model

### ISSUE THREAD

**Issue by jonbcampos** [scambra/devise_invitable#608]
I have three devise models (ie. User, Admin, SuperAdmin).

When I try to invite a user (new_user_invitation_path) from an Admin I get a warning that the user isn't signed in.

How would I make the change so that Users can be invited by Admins? How do I get in the way of the before_filter?

**Comment by scambra** [comment]
Explained in README, controller filter section. You can override authenticate_inviter! filter on ApplicationController. In your case should be:

```ruby
def authenticate_inviter!
    authenticate_admin!(:force => true)
  end

**Comment by jonbcampos** [comment]
sorry, can't believe I missed that part. I really thought I read it up and
down

On Mon, Nov 30, 2015 at 10:41 PM, Sergio Cambra <notifications@github.com>
wrote:

> Explained in README, controller filter section. You can override
> authenticate_inviter! filter on ApplicationController. In your case should
> be:
>
> def authenticate_inviter!
>     authenticate_admin!(:force => true)
>   end
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scambra/devise_invitable/issues/608#issuecomment-160851338>
> .
>



-- 
Jonathan Campos

**Comment by scambra** [comment]
Never mind, README is long
