### ISSUE TITLE
RAILS 5 error : alias_method': undefined method `attributes_for' for class `Devise::ParameterSanitizer

### ISSUE THREAD

**Issue by dlupu** [scambra/devise_invitable#616]
Hello, 

I'm trying to migrate one of my apps from Rails 4.2.6 to Rails 5.0.0.beta1. I'm using master branch of devise because it has Raills5 support. 

I'm getting an `'alias_method': undefined method `attributes_for' for class `Devise::ParameterSanitizer' (NameError) error` when I try to execute my tests :

Full BackTrace is available in this [gist](https://gist.github.com/dlupu/d37fbf706ca307145bfe)

As far as I can see this is related to [this recent commit](https://github.com/plataformatec/devise/commit/df8b48646b0d0bc10d07c7757d8a841e85f77a37) that changed the internals of `Devise:: ParameterSanitizer`

**Comment by scambra** [comment]
Fixed on #619

**Comment by ssreddyror** [comment]
plz need help to me undefined method `attributes_for' for class `Devise::ParameterSanitizer'
this error

**Comment by scambra** [comment]
DeviseInvitable has fixed the error, ensure you are using latest version
