### ISSUE TITLE
Callbacks for `invited` missing

### ISSUE THREAD

**Issue by manygrams** [scambra/devise_invitable#617]
@scambra I noticed that [here](https://github.com/scambra/devise_invitable/blob/5c4260faf54ae010e0aef2674fed37f504cebfa3/lib/devise_invitable/model.rb#L83-L87) you have callbacks wrapping the `accept_invitation!` method. Are you interested in similar callbacks wrapping `invite!`?

I'd find it useful for something I'm working on, but I realize it's somewhat similar to something like a `after_create :callback_method, if: invitation_created_at _not_nil` callback on the invitable model. However, I think it would be nice that the callback would be the one true source for running callbacks before and after an invite is sent.

If you're interested, let me know, and I'll open a PR.

**Comment by scambra** [comment]
nice, I could merge that PR
