### ISSUE TITLE
helper_method not present in rails 5 API mode

### ISSUE THREAD

**Issue by jeryRazakarison** [scambra/devise_invitable#620]
I'm trying to use devise_invitable with rails 5 API mode. But when I try to `rails s`, I have an error:
```
/Users/jery/.rvm/gems/ruby-2.2.2/bundler/gems/devise_invitable-d7d24fc41141/app/controllers/devise/invitations_controller.rb:7:in `<class:InvitationsController>': undefined method `helper_method' for Devise::InvitationsController:Class (NoMethodError)
        from /Users/jery/.rvm/gems/ruby-2.2.2/bundler/gems/devise_invitable-d7d24fc41141/app/controllers/devise/invitations_controller.rb:1:in `<top (required)>'
        from /Users/jery/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:492:in `load'
        from /Users/jery/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:492:in `block in load_file'
        from /Users/jery/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:682:in `new_constants_in'
```

This is because rails api doesn't include helper support?

Does someone know how to work with rails 5 API and devise_invitable?

Thank you for any help.

Jery

**Comment by jeryRazakarison** [comment]
(I know that in the Devise gem, they wrapped the `helper_method`calls with respond_to?
https://github.com/posgarou/devise/commit/a3da40a701197961d8eae0ca0cf75300a85b7cf2

**Comment by jeryRazakarison** [comment]
I ended up stubbing `helper_method`in the application_controller.rb
```
 def self.helper_method(*args)

  end
```
I know this is a temporary method as it can break functionalities of other gems. If anyone has a better way, I take it ^^

Jery

**Comment by scambra** [comment]
Why helper_method doesn't exist? I can still see in master branch:
https://github.com/rails/rails/blob/master/actionpack/lib/abstract_controller/helpers.rb#L60

Just trying to understand why is needed

**Comment by Shwetakale** [comment]
@scambra helper_method doesn't exist for rails api. It still exist for rails project and @jeryRazakarison is creating rails api.
