### ISSUE TITLE
Validate a resource when/after accepting an invitation ?

### ISSUE THREAD

**Issue by Kosmin** [scambra/devise_invitable#621]
I've come across the following use case quite often in some of my previous projects and I'd like to submit a fix for this, if everyone else can agree that this is something that the community needs.

**The use case**
1. an invitation is sent to a user
2. the user is redirected to a custom page for an extension of `Devise::InvitationsController`
3. the user *MUST* accept terms of agreement before proceeding.

**The Problem**
The problem here is that I need to validate `user.terms_accepted_at.present?`, but only IF the invitation was accepted. Otherwise, the validation for terms of agreement should apply only when/after accepting the invitation.

Also, I could just overwrite the `accept_resource` method and run validations in there, but this really isn't too great, not to mention I want to memoize the callbacks, and this quickly turns into scope creeping e.g.:
```ruby
def accept_resource
  run_callbacks :validations_for_invitations
    resource_class.accept_invitation!(params)
  end
end
```

**Solutions**
1) I am proposing the following solution: can we run validations inside the block for `:invitation_accepted` callbacks (lib/devise_invitable/model.rb), e.g.:
```ruby
def accept_invitation!
  run_callbacks :invitation_accepted do
    if self.invited_to_sign_up? && self.valid?
      self.accept_invitation
      self.confirmed_at = self.invitation_accepted_at if self.respond_to?(:confirmed_at)
      self.save(:validate => false)
    end
  end
end
``` 

2) Another way of doing it is to include validations SPECIFICALLY for the invitation process, e.g.:
```ruby
define_callbacks :invitation_validations, terminator: ->(target, result) { result == false }

#...

def accept_invitation!
  if self.invited_to_sign_up? && self.valid?
    run_callbacks :invitation_validations do
      run_callbacks :invitation_accepted do
        self.accept_invitation
        self.confirmed_at = self.invitation_accepted_at if self.respond_to?(:confirmed_at)
        self.save(:validate => false)
      end
    end
  end
end
```

3) In my opinion the cleanest way, why not just validate again in order to save the resource, e.g. don't use `self.save(:validate => false)`, and just follow rails error handling conventions ?
```ruby
def accept_invitation!
  # ...
  self.save()
  # ...
end
```

**Comment by scambra** [comment]
I don't understand your third proposal. Do you mean have this code for accept_invitation!?

```ruby
      def accept_invitation!
        if self.invited_to_sign_up?
          run_callbacks :invitation_accepted do
            self.accept_invitation
            self.confirmed_at = self.invitation_accepted_at if self.respond_to?(:confirmed_at)
            self.save
          end
        end
      end
```

With this change I guess invitation_accepted callbacks will run even if validations fails. Probably it's ok for before callbacks, but I don't think running after callbacks when validations fails is good idea.

I think you can do this in your model, without changing nothing on devise invitable:

```ruby
attr_reader :accepting_invitation
validates :terms_accepted_at, :presence => true, :if => :accepting_invitation
def accept_invitation!
  @accepting_invitation = true
  super
end

**Comment by Kosmin** [comment]
Well, first of all thanks for responding so quickly! 

> I don't understand your third proposal. Do you mean have this code for accept_invitation!?

Actually no. What I meant is have the exact same code, but call `self.save` without `(:validate => false)`. This way, if any validations rely on `invitation_accepted_at`, they will simply be triggered on save and the invitation will not be accepted:

```ruby
def accept_invitation!
  if self.invited_to_sign_up? && self.valid?
    run_callbacks :invitation_accepted do
      self.accept_invitation
      self.confirmed_at = self.invitation_accepted_at if self.respond_to?(:confirmed_at)
      self.save
    end
  end
end
```

This way, the `:invitation_accepted` callbacks don't end up running if the model is not valid to begin with.

The only problem might be that the invitation `save` fails, and `:invitation_accepted` after callbacks are still run. But that is fixed with:

```
set_callback :do_something, :after,  :accept_invitation, if: :valid?
```

**Comment by scambra** [comment]
I added accepting_invitation? method, you can use that as conditional in your validations, so terms acceptation is only check when invitation is being accepted.

```ruby
validates :terms_accepted_at, :presence => true, :if => :accepting_invitation?

**Comment by Kosmin** [comment]
That solution makes sense, and thank you for putting this in. But I must ask: why do you have to call `self.save(:validate => false)` on line 96 ? Why not just do `self.save` ?

**Comment by scambra** [comment]
because valid? is already called so I don't see why run again validations

**Comment by Kosmin** [comment]
I agree, validations shouldn't rerun. It completely slipped my mind when I posted the code above.

What I was leaning towards is: why not just allow `self.save` to run the validations, instead of running them before running the `accept_invitation` callbacks?

```
if self.invited_to_sign_up?
  run_callbacks :invitation_accepted do
    self.accept_invitation
    self.confirmed_at = self.invitation_accepted_at if self.respond_to?(:confirmed_at)
    self.save
  end
end
```

But now I realize that if the save fails, we also have to break out of the `invitation_accepted` callbacks and not run the `:after` callbacks, maybe using the callbacks `terminator:`.

This allows others to create validations on the `confirmed_at` field and `accepted_at` field (i.e. can't accept an invitation on the weekends), without having to think of how the `devise_invitable` gem is implemented. What do you think ?

**Comment by scambra** [comment]
I was able to change this without changing current behaviour (I hope so, tests pass)

**Comment by Kosmin** [comment]
That's brilliant! I'll rerun things on my end later today and help double check that everything works as expected. Thanks so much!

**Comment by Kosmin** [comment]
So I ran things on my end and it seems in order to make sure `after_invitation_accepted` callbacks **don't** run, the callbacks also need a terminator:

```
    define_model_callbacks :invitation_created
    define_model_callbacks :invitation_accepted, terminator: ->(target, result) { result == false }
```

Also, it seems like there's no more need for @accepting_invitation. I tried taking that out but some of the tests started failing so I'll try to look more into that before submitting a PR

**Comment by scambra** [comment]
terminator shouldn't be needed, I have test for that, because define_model_callbacks already set that terminator. What rails version are you using?

@accepting_invitation is needed, if validation fails, invited_to_sign_up will be false because we don't have token (although it's present on db), but I fixed returning true if accepting invitation. Also, when accepting, on validations invitation_accepted? would return true, but it's not accepted really yet, so I return false checking @accepting_invitation
