### ISSUE TITLE
DEPRECATION WARNING: alias_method_chain is deprecated

### ISSUE THREAD

**Issue by Fudoshiki** [scambra/devise_invitable#623]
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from require at ~/.rvm/gems/ruby-2.3.0/bundler/gems/devise_invitable-d9613aeac27c/lib/devise_invitable.rb:12)

**Comment by interhive** [comment]
Also seeing this in these two files:

```console
/devise_invitable/lib/devise_invitable/mapping.rb:4
/devise_invitable/parameter_sanitizer.rb:17
```

**Comment by scambra** [comment]
Is it from rails5?

**Comment by interhive** [comment]
Yes, it does appear that the deprecation warnings only affect Rails 5 right now, which is still in beta. I suppose that means it will be a while before it is actually deprecated -- perhaps Rails 5.1.

I don't see a clean solution that will work like the `prepend_before_filter` patch. I guess we can look around and see how other projects are handling it. I imagine they're punting it down the road for the time being.
