### ISSUE TITLE
add invitation strategy

### ISSUE THREAD

**Issue by gingray** [scambra/devise_invitable#637]
Hi @scambra i'm using this gem thank you and all other developers for it. Also i've face with some sort of issue if it can be named so like let me provide example. In our service we use gem to help people to collaborate subscription depends on how many people are involved in collaboration. Gem using decrement strategy and it's a little bit inconvenient for example to calculate all invited people i need to do stuff like this
```
total_users = user.invitations_count + user.invitation_limit
```
or for update subscription
```
  def can_change_plan?
    user.invitations_count < plan.invitation_limit && user.plan_id && user.plan_id != plan.id
  end

  def plan_change!
    raise error_msg unless can_change_plan?
    user.transaction do
      user.update! invitation_limit: invitation_limit
      user.update! plan: plan
    end
  end

  def invitation_limit
    plan.invitation_limit - user.invitations_count
  end
```

How do you think will be it a good idea to add in gem some sort of invitation strategy with backward compatibility. In default it will be decrement invitation_limit each time user invite but if settings set like
```
class Invitable < User
  devise :invitable, invite_for: 5.days, invite_strategy: :increment
end
```
it will be check if 
```
user.invitations_count <= user.invitation_limit
#then can invite
```
It helps to change ability to invite users more flexible and can be more intuitive. I can make a pull request with this kind of changes if you think that this improvements make sense. Thanks.

**Comment by scambra** [comment]
Yes, I would accept that pull request

**Comment by gingray** [comment]
@scambra sorry for long response when it will be done i'll make pull request.
