### ISSUE TITLE
NameError - undefined local variable or method `this' 

### ISSUE THREAD

**Issue by mikevic** [scambra/devise_invitable#639]
When trying to set up the password, I get the following error : 

`NameError - undefined local variable or method `this' for #<Users::InvitationsController:0x007f9cbbe341f8>:
  app/controllers/users/invitations_controller.rb:3:in `update'`

As in the documentation, this is users/invitations_controller.rb

```ruby
class Users::InvitationsController < Devise::InvitationsController
  def update
    if this
      redirect_to root_path
    else
      super
    end
  end
end
```

Am I doing something wrong?

**Comment by scambra** [comment]
there is no this variable or method in your controller

**Comment by Aerlinger** [comment]
Yeah, not sure why this is in the docs. I believe `this` is supposed to be the invitation resource.

**Comment by scambra** [comment]
It was a bad example, it's a too generic non-sense example because it's not trying to do any specific thing, only explaining how to create your own controller.
