### ISSUE TITLE
Invitation can be accepted without password

### ISSUE THREAD

**Issue by johnathanludwig** [scambra/devise_invitable#643]
I've discovered that an invitation can be accepted without submitting a password if the password params are not present on the request.

#### Steps to Reproduce
1. Invite User
2. Go to invitation URL
3. Delete password fields from the form (using dev tools).
4. Submit the form. The invitation will be accepted and you will be signed in.

**Comment by scambra** [comment]
Are you using validatable in your model? Have you changed some validations or defined invited_to_sign_up or block_from_invitation methods?

**Comment by johnathanludwig** [comment]
Yes, I tested with a new rails app and installed just devise + devise_invitable. It is using validatable.

I've written a failing test case, but haven't had the time to look into fixing it.

`test/models/invitable_test.rb`
```ruby
test 'should not accept invite without password' do
  user = User.invite!(:email => "valid@email.com")
  user = User.accept_invitation!(:invitation_token => Thread.current[:token])
  refute_predicate user, :invitation_accepted?
end
```
