### ISSUE TITLE
Could an invite be sent via text?

### ISSUE THREAD

**Issue by SupremeA** [scambra/devise_invitable#647]
Can I configure devise_invitable to send an sms along with the email? I am trying to set it up using twilio. Any steps or instructions on is this possible? I am trying to pass the login link thru the text message.

**Comment by scambra** [comment]
If you can configure devise to send sms, you can configure devise_invitable. Devise_invitable just uses send_devise_instructions method to send email

**Comment by SupremeA** [comment]
Understood, thanks!
