### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by julianguyen** [scambra/devise_invitable#648]
I'm trying to follow the installation steps, however when I get to the automatic installation section and run `rails generate devise_invitable:install`

I get the following error:
`"alias_method': undefined method 'attributes_for' for class 'Devise::ParameterSanitizer' (NameError)`

I have the latest version of Devise installed i.e. 4.1.0 in Rails 4

**Comment by scambra** [comment]
Update devise invitable version, attributes_for is not aliased anymore, so you must be using old version

**Comment by julianguyen** [comment]
@scambra What is the correct way to do that? `bundle update` ?
