### ISSUE TITLE
How to add custom fields in User.invite!

### ISSUE THREAD

**Issue by ashwinputhige** [scambra/devise_invitable#649]
I am unable to save my custom field `phone` when I pass it as a param to invite!. 
I have also defined `attr_accessor :phone` in User.rb.

```
@user = User.invite!({:email => email,  :phone => phone}, current_user) do |u|
    u.skip_invitation = true
end
```

What am I missing?

**Comment by scambra** [comment]
attr_accessor must not be used for columns, attr_accessor define a setter like this:

```ruby
def phone=(value)
  @phone = value
end
```

So phone column will never be saved

**Comment by ashwinputhige** [comment]
@scambra Thank You. Its working now. I don't know how I fixed it but I think it was a server restart that fixed it. 
Also removed  `attr_accessor`. I added it after reading this(`You can add :skip_invitation to attributes hash if skip_invitation is added to attr_accessible`) line in the doc and thought that its required for some reason.
