### ISSUE TITLE
How to create a controller file

### ISSUE THREAD

**Issue by karthickms** [scambra/devise_invitable#657]
Hi All,

I am using following command for invite friends

in Gemfile
-------------------------------
gem 'devise_invitable', '~> 1.5.2'   and entered following commands in terminal

budle install
bundle exec rails generate devise_invitable:install
bundle exec rails generate devise_invitable:views

Views file are generated but controller files are not generated. What should I do and what the next steps to get it. Please hands to me

**Comment by scambra** [comment]
You don't need to generate controllers if you don't need to change anything, really you don't need to generate views if default views are ok for you.

If you need a controller, create it by yourself, create it blank file or use rails g controller, then follow steps on README: https://github.com/scambra/devise_invitable#configuring-controllers

**Comment by karthickms** [comment]
Then, When my enter the following URL it returns 

No route matches [GET] "/users/invitations"
No route matches [GET] "/users/invitations/new"

What Should I do

**Comment by scambra** [comment]
You missed rails generate devise_invitable User

**Comment by karthickms** [comment]
Yes. I have missed the code your pointed out on my first chatting in this loop. But on my code i have correctly do it. Like as

gem 'devise_invitable', '~> 1.5.2'
bundle install
bundle exec rails generate devise_invitable:install
bundle exec rails generate devise_invitable user
bundle exec rake db:migrate
bundle exec rails generate devise_invitable:views

But it will returns
No route matches [GET] "/users/invitations"
No route matches [GET] "/users/invitations/new"

**Comment by scambra** [comment]
Check if :invitable is added to devise line in user model

**Comment by karthickms** [comment]
Yes. Here is my code 
user.rb    --> app/models
------------------------------------
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

**Comment by scambra** [comment]
Did you add devise_for :users to your routes? It isn't in README of DeviseInvitable, because it's a needed step for devise

**Comment by karthickms** [comment]
In my routes.rb
---------------------------------
devise_for :users, :controllers => { :invitations => 'users/invitations' }
---------------------------------
how can I execute it?.

**Comment by scambra** [comment]
what's output for rake routes CONTROLLER=users/invitations?

**Comment by karthickms** [comment]
Sorry, I didn't get your point.

But when I entered following two URL it returns "ActionController::RoutingError No routes matches"
"/users/invitations"
"/users/invitations/new"

**Comment by scambra** [comment]
There is something wrong in your app, you must have config/routes.rb with:

```ruby
Rails.application.routes.draw do
  devise_for :users, :controllers => { :invitations => 'users/invitations' }
  [other routes for your app]
end
```

Or your file is missing or something is wrong with file and rails find no routes.
rake routes in terminal should list all routes defined for your app

**Comment by karthickms** [comment]
Here I shared the screen shot of my all routes

![inv_friend](https://cloud.githubusercontent.com/assets/16956722/16223411/c3960a4e-37ba-11e6-82cd-635ee15869b0.png)

/users/sign_in only workable but I don't know the username and password. And all other routes are No routes matches is only displayed

Please help me !!!!!

**Comment by scambra** [comment]
Probably you wrote wrong command when looking for invitations routes:

bundle exec rake routes CONTROLLER=users/invitations

? should not added to command, I was asking you

Anyway, you can see all routes in that screenshot, you can see there is no /users/invitations route, it's /users/invitation but POST, not GET, to create invitation with form. And there is no route /users/invitations/new, it's /users/invitation/new. So you should open /users/invitation/new in your browser

**Comment by karthickms** [comment]
Here I using production mode for application, not development mode.

for production mode, we should use "bundle exec" keyword before the command "rake routes CONTROLLER=users/invitations?"

When  "/users/invitation/new" it should returns

RuntimeError (Circular dependency detected while autoloading constant Users::InvitationsController)

**Comment by scambra** [comment]
bundle exec doesn't harm, ensure gem versions from gemfile are loaded.
About circular dependency, you may have wrong parent controller for Users::InvitationsController, is it class Users::InvitationsController < Devise::InvitationsController?

**Comment by karthickms** [comment]
Can I know, where should I changed this ?

class Users::InvitationsController < Devise::InvitationsController

**Comment by scambra** [comment]
You created users/invitations_controller.rb becuase you want to change some controller behaviour, or add some methods. That controller must inherit from Devise::InvitationsController

**Comment by karthickms** [comment]
Then I have one doubt about this, Now I changed in **routes.rb** is it right?

in **routes.rb** 
---------------------------
devise_for :users   
instead of 
devise_for :users, :controllers => { :invitations => 'users/invitations' }

**Comment by scambra** [comment]
If you have devise_for :users, you will use default controller (Devise::InvitationsController, provided by devise_invitable gem), not your controller.

[Configuring controllers](https://github.com/scambra/devise_invitable/#configuring-controllers) is pretended to change default behaviour, if you don't need to change the controller's behavior, you don't need to generate your own controller and you don't need to change routes, you can use devise_for :users

**Comment by karthickms** [comment]
Yes. Thanks now working. 

But the links are not shown. 
Manually I entered the URL when user login and logout

**Comment by scambra** [comment]
There is no default link, you can add it to your layout or any view you want to have link to invite

**Comment by karthickms** [comment]
Okay. well

When user click a Accept invitation friend link, the invitation is not accepted. What I do?
