### ISSUE TITLE
Sometimes my site is 500 internal server error happen

### ISSUE THREAD

**Issue by karthickms** [scambra/devise_invitable#658]
Hi All,

Sometimes my site is 500 internal server error happen. Here I shared the screenshot

![2016-06-18 18-24-12](https://cloud.githubusercontent.com/assets/16956722/16171008/95dd4b10-3582-11e6-9aa6-38af34a31fb2.png)

Please help me !!!!!....

**Comment by scambra** [comment]
You need to check your log/productio.log file, in that error no info is displayed, it may be related to devise invitable or anything else

**Comment by karthickms** [comment]
It returns in production.log

ActiveRecord::ConnectionTimeoutError (could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)):
  lib/middleware/security.rb:11:in `call'

**Comment by scambra** [comment]
You have an issue with database connection, not related to devise_invitable
