### ISSUE TITLE
Is there a way for User to trigger Resend Invitation Email ?

### ISSUE THREAD

**Issue by san** [scambra/devise_invitable#659]
If an invitee misplaces the invitation email, is there a way for them to trigger receiving the invitation email again? Similar to the link that says "Didn't Receive Confirmation Instructions?"

Because when a user is invited, but instead of clicking on the link in the email they try to login, they get an error that says "You have a pending invitation, accept it to finish creating an account". But if they have lost the email, they can't do anything.

Any ideas?

**Comment by scambra** [comment]
They should be able to use reset password

**Comment by san** [comment]
That is correct. Resetting the password does work. But it's not very intuitive though.

**Comment by scambra** [comment]
You can change translation to give hint to users about using reset password if they have lost invitation email
