### ISSUE TITLE
Pass a variable to the subject ?

### ISSUE THREAD

**Issue by Sashkan** [scambra/devise_invitable#660]
I know it is possible to change the subject of the invitation_instructions mail by setting our own in devise_invitable.fr.yml . I saw that a ```url``` var is passed to the translation. How can I set another variable ?

I would like to set the subject to 
``` %{user} has invited you to join %{url}```

Is it possible ?

**Comment by scambra** [comment]
You can create mailer views in your app and pass any variable you want:
app/views/devise/mailer/invitation_instructions.html.erb
app/views/devise/mailer/invitation_instructions.text.erb

**Comment by jabbett** [comment]
But the views only control the content of the e-mail, right? The subject is defined in the locale file(s). Are there any variables that are passed into that translation string?

**Comment by scambra** [comment]
Sorry, that's about email content, for email subject you may use headers_for(action, opts) method in the model. :
https://github.com/plataformatec/devise/blob/master/lib/devise/mailers/helpers.rb#L29

**Comment by scambra** [comment]
DeviseInvitable uses devise methods to send email, deliver_invitation method has options hash which is used in mailer to override parameters of mail method, so you can override deliver invitation in your model to change subject

Original method
```ruby
      def deliver_invitation(options = {})
        generate_invitation_token! unless @raw_invitation_token
        self.update_attribute :invitation_sent_at, Time.now.utc unless self.invitation_sent_at
        send_devise_notification(:invitation_instructions, @raw_invitation_token, options)
      end
```

Overrided method:
```ruby
def deliver_invitation(options = {})
  super(options.merge(subject: ...))
end
```

Also, you can override devise mailer to change subject. Devise_invitable only uses devise_mail method in mailer, there you can override subject_for method in mailer:

Method from devise:
```ruby
      def subject_for(key)
        I18n.t(:"#{devise_mapping.name}_subject", scope: [:devise, :mailer, key],
          default: [:subject, key.to_s.humanize])
      end
```

https://github.com/plataformatec/devise/wiki/How-To:-Use-custom-mailer
