### ISSUE TITLE
Invitations sent to multiple people

### ISSUE THREAD

**Issue by aymericbouzy** [scambra/devise_invitable#663]
I'm currently editing the default view and controller to be able to invite multiple people at the same time. I've added a '+' button that adds an email field to my form each time I click on it. The controller then receives an array of email addresses (thanks to the `multiple: true` attribute provided to the form field, and does the same job it does for a single element to each member of the array.
Would it be interesting to integrate this to the gem ? There are a few things to figure out, but if it is something you're interested in, we can figure out an API and I can do a PR.

**Comment by LeKristapino** [comment]
I think it is pretty clear how to make this work. A separate API for this might be even harder to understand than the basic approach, what you described. In my opinion a section in WIKI could suffice

**Comment by aymericbouzy** [comment]
in fact I gave up, and created a separate view altogether. the problem I had is that devise only manages one resource at a time, and I couldn't find how to manage multiple ones.

**Comment by scambra** [comment]
I think it's better wiki page with instructions

**Comment by aymericbouzy** [comment]
I'm going to need a CSV document uploader too, this is getting bigger than I thought.

**Comment by scambra** [comment]
Definitely, too much for adding to devise_invitable, wiki page or new gem extending invitable are better
