### ISSUE TITLE
Support for Devise 4.1 / 4.2?

### ISSUE THREAD

**Issue by maia** [scambra/devise_invitable#667]
As `1.6.0` specifically supports devise 4.0, does it also support 4.1 and 4.2? I've seen a mention of 4.1 in recent commits, but no version push has been made since. Thanks!

**Comment by scambra** [comment]
Devise 4.1 worked too, a test was failing, but it was a bug in tests. I'm releasing 1.6.1, but 1.6.0 works with 4.1.
Tests are failing for devise 4.2 so probably something needs to be fixed.

**Comment by scambra** [comment]
It works with devise 4.2 (at least devise_invitable >= 1.6.0), but tests needed to be updated

**Comment by maia** [comment]
@scambra Thanks a lot for investigating!
