### ISSUE TITLE
 Invited by can't be blank :: Want to make model skip validation for admin

### ISSUE THREAD

**Issue by shivabhusal** [scambra/devise_invitable#669]
Hey Guys, I stumbled upon an error like
```
 Invited by can't be blank
```

I have models `Teacher`, `Operator`, `Admin` inherited from `User` model. And, `Admin` is the only person that can invite others. I want to the ` Invited by can't be blank` validation skipped by the `Admin` model.

Is there any clean way to do that?

For now, in `factory_girl` I did  like 

Inside the factory:
```
to_create {|instance| instance.save(validate: false) }
```

**Comment by scambra** [comment]
what rails version?

**Comment by scambra** [comment]
invited_by shouldn't be required, deviseinvitable shouldn't add presence validation for invited_by. DeviseInvitable 1.6.0 enables :optional on rails 5 (a new option on rails 5)

**Comment by shivabhusal** [comment]
hey @scambra there go the versions of libraries I have been using
```
Rails: 5.0
Mongoid: 6.0.0 beta
Devise: 4.2.0
Devise Invitable: 1.6.0
Rspec: 3.5.0
Factory Girl: 4.7.0
```

**Comment by scambra** [comment]
mongoid has :optional support too, added to 6.0.0 beta, I just added support for it (see #662), no released version yet
