### ISSUE TITLE
user.invitation_accepted? returns FALSE after calling user.accept_invitation!

### ISSUE THREAD

**Issue by tom-lord** [scambra/devise_invitable#674]
I believe this is a bug introduced in gem version `1.6.1` (and `1.7.0`), in the following commit:

https://github.com/scambra/devise_invitable/commit/244e8c230dd0712ad54cdf0b79af4a163b9a315c

Namely, in the following line of code:

```
   def invitation_accepted?
-     invitation_accepted_at.present?
+    !accepting_invitation? && invitation_accepted_at.present?
   end
```

Based on my limited understanding, I think the issue is that [`@accepting_invitation`](https://github.com/scambra/devise_invitable/blob/244e8c230dd0712ad54cdf0b79af4a163b9a315c/lib/devise_invitable/model.rb#L92) only ever gets set to `true` - even though the flag is supposed to be for "when an invitation accept is _in progress_"? In which case, the solution would simply be to add `@accepting_invitation = false` [here](https://github.com/scambra/devise_invitable/blob/244e8c230dd0712ad54cdf0b79af4a163b9a315c/lib/devise_invitable/model.rb#L97).

**Comment by scambra** [comment]
If you reload user, does invitation_accepted? return true?

**Comment by tom-lord** [comment]
Nope

**Comment by scambra** [comment]
Provide a failing test, please

**Comment by tom-lord** [comment]
Fairly self-explanatory, but here is a failing test as I described above: https://github.com/tom-lord/devise_invitable/commit/be24ca5cb01862d8663af8a738db578960af2400

Unless I'm misunderstanding the meaning of `@accepted_invitation`?... I'm a little unclear what that variable is supposed to be representing.

**Comment by sivagollapalli** [comment]
@tom-lord I think we need to test case little bit where `new_user` doesn't add `invitation_token` to object.

```
 test "invited_at? should return true after invitation is accepted" do                                       
    user = new_user(invitation_token: '1234567890')                                                           
    refute user.invitation_accepted?                                                                          
    user.accept_invitation!                                                                                   
    assert user.invitation_accepted?                                                                          
  end 
```

**Comment by tom-lord** [comment]
Perhaps I should have stuck a `user.invite!` in there actually, but still - the "bug" I described seems to persist.

**Comment by tom-lord** [comment]
Just revisiting this old issue... It seems @dandrews went ahead and fixed this issue (exactly how I described above) here: https://github.com/scambra/devise_invitable/pull/710

The last gem version release (28 March 2017) was prior to that change (5 May 2017) however. It would be great to see another update, that includes this fix 😄 

Anyway, I'll mark this issue as closed!

**Comment by scambra** [comment]
I wil release when I have time to test against devise 4.4

**Comment by SirRawlins** [comment]
@tom-lord @scambra - Thanks for the fix on this! Found myself scratching my head today trying to figure out why things weren't working as I'd expect.
