### ISSUE TITLE
Getting error when setting invited_by_class_name as parameter directly in the devise method - Need example

### ISSUE THREAD

**Issue by secondstreetmedia** [scambra/devise_invitable#677]
When setting the devise method in my AdminUser model as follows:

    devise  :database_authenticatable,
            :lockable,
            :recoverable,
            :registerable,
            :rememberable,
            :timeoutable,
            :trackable,
            :validatable,
            :invitable,
            :invited_by_class_name  => 'SuperAdminUser'

I'm getting the following error in the console when running my migrations:

    NoMethodError: undefined method 'invited_by_class_name=' for AdminUser (call 'AdminUser.connection' to establish a connection):Class

Any idea what might be causing this? Does a complete example of implementing devise_invitable in this manner exist?

**Comment by sivagollapalli** [comment]
@secondstreetmedia Could you provide sample app or test case to reproduce this error?

**Comment by scambra** [comment]
I forgot to enable setting invited_by_class_name on model, it was working only on initializer (global config). Same for invited_by_foreign_key and invited_by_counter_cache.

**Comment by secondstreetmedia** [comment]
Awesome, thanks!!!
