### ISSUE TITLE
Is Resource a reserved Name ?

### ISSUE THREAD

**Issue by Sashkan** [scambra/devise_invitable#678]
Hello,

I created a ```Resource``` model on my app. Everything seemed to work fine for a while, but a few hours ago, I updated my model (no big deal, just added a ```text``` field on it).

But now, everytime I get the following error: 
```
undefined method `invite_key_fields' for #<Class:0x0056293b5d6bb8>
```
on this line :
 ```
<% resource.class.invite_key_fields.each do |field| -%>
```

and the matching ```resource``` is the following:
```
#<Resource id: nil, created_at: nil, updated_at: nil, file_file_name: nil, file_content_type: nil, file_file_size: nil, file_updated_at: nil, brief_id: nil, uploader_id: nil>
```

How comes so ? Is there a conflict between Devise Resource and mine ?

**Comment by scambra** [comment]
Not reserved on devise invitable, but devise invitable is only a devise extension. You should ask to devise, probably they will know better if there is an issue with naming a model as Resource.
