### ISSUE TITLE
Disable Password Changed notification when some one accept the invitation

### ISSUE THREAD

**Issue by sahilchopra** [scambra/devise_invitable#679]
In Device.rb

Devise.setup do |config|
  # Send a notification email when the user's password is changed
  config.send_password_change_notification = true
end

**Comment by SirRawlins** [comment]
Has anyone got a workaround for this? If not I'll be happy to set about a PR to resolve it. Or is it something which should be tackled upstream? Perhaps Devise callbacks should be checking if the `password changed_from == nil` instead of just a basic change on the attribute to and from anything.

**Comment by SirRawlins** [comment]
Someone here on the Devise list discussing a flag to allow skipping the email on a per-request basis which might be ideal for what we want to do here.

https://github.com/plataformatec/devise/issues/4492

The only other workable option would perhaps be to monkey-patch over Devises internal methods which do the logic to determine if the email should be sent.

**Comment by SirRawlins** [comment]
Had a look this morning at options for MonkeyPatching and I couldn't see any approach which would be stable and reliable.

I think Devise needs to add a way to natively skip this email to it's API, as it does with confirmation emails, we can then interact with that API from invitable to skip sending password change emails when accepting an invite.

If anyone else has any short-term solutions I'd love to hear them, as getting a PR upstream is likely to take a little while.

**Comment by adzap** [comment]
My solution was override (monkey path) in model like so 

`
def send_password_change_notification?
  super && encrypted_password_was.present? # it will be an empty string by default
end
`

**Comment by scambra** [comment]
@adzap could you send a pull request?

**Comment by adzap** [comment]
sure thing. but I was wondering if `accepting_invitation?` is a better/safer check. Thoughts?

**Comment by scambra** [comment]
You're right, it would be safer, in case someone has empty encrypted passwords and wants password change notifications
