### ISSUE TITLE
Login avoid accept invite

### ISSUE THREAD

**Issue by JIucToyxuu** [scambra/devise_invitable#683]
Hello! I found strange situation when invited user can just reset password by 'devise' and so login without accept invitation. So, invitation_token don't have sense.

**Comment by JIucToyxuu** [comment]
I think this happened because this keep users together(not accepted and accepted) and so 'devise' just work with this identically.

**Comment by scambra** [comment]
invitation token makes sense because you can use it without reset password, but if user deletes invitation email, it can "accept" invitation using reset password feature. It works like that by design.
