### ISSUE TITLE
Quick question: Can two or more users invite the same person (email) ?

### ISSUE THREAD

**Issue by gbrl** [scambra/devise_invitable#684]
Since this gem creates a User record in the DB upon inviting someone, does this mean two different users  can't invite the same person (email)?

**Comment by scambra** [comment]
They can invite same person if resend_invitation is enabled, which is default

**Comment by gbrl** [comment]
Thank you!!!

**Comment by gbrl** [comment]
So the most recent user to send the invitation gets the "credit" when the invited person signs up?

**Comment by scambra** [comment]
Yes, because previous invited_by association is changed to new one, and previous invitation_token is changed with new one, so previous invitation doesn't work anymore
