### ISSUE TITLE
Unable to access users/password/edit

### ISSUE THREAD

**Issue by SimonDKnight** [scambra/devise_invitable#687]
Hi, I am having an issue hitting the url users/password/edit. It either asks me to login, which I then do, or it says "You are already signed in." if i am signed in and try to go to that URL. In the rails console I am seeing 

"Filter chain halted as :require_no_authentication rendered or redirected"

Any ideas?

I want to allow users to reset their password, or at least use the forgotten password link to reset their password (the url users/password/new) also does not work if they are logged in (but works if they are not logged in).

**Comment by SimonDKnight** [comment]
OK I figured it out. So the password/edit is only available via the email link sent to the user when invited and is not actually used to edit the password.

**Comment by scambra** [comment]
It should be users/invitation/accept, users/password/edit is related to devise confirmable module, not devise invitable
