### ISSUE TITLE
How do I pass params to my devise_invitable controller?

### ISSUE THREAD

**Issue by marcamillion** [scambra/devise_invitable#690]
I have created an invitation controller that is quite vanilla:

    class InvitationsController < Devise::InvitationsController
      def new
        binding.pry
      end
    end

And I created a link that triggers that request like so:

    <%= link_to "Invite #{@profile.name}", new_user_invitation_path(email: @profile.email), class: "btn btn-xs btn-primary" %>

The issue I am having is that when I get thrown into pry in that action, it doesn't show me that `email` parameter.

    > params
    => <ActionController::Parameters {"controller"=>"invitations", "action"=>"new"} permitted: false>

How can I send params with that `InvitationsControler#New` action?

**Comment by scambra** [comment]
Can you post log for that request?

**Comment by marcamillion** [comment]
@scambra Sure. Here you go:

```
Started GET "/users/invitation/new" for ::1 at 2016-10-26 11:58:45 -0500
Processing by InvitationsController#new as HTML
  User Load (5.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 2], ["LIMIT", 1]]
  Rendering devise/invitations/new.html.erb within layouts/application
  Rendered devise/invitations/new.html.erb within layouts/application (721.1ms)
Completed 500 Internal Server Error in 801ms (ActiveRecord: 5.2ms)


DEPRECATION WARNING: #original_exception is deprecated. Use #cause instead. (called from initialize at /.rvm/gems/ruby-2.3.1@myapp-rails-5.0/gems/better_errors-2.1.1/lib/better_errors/raised_exception.rb:7)
DEPRECATION WARNING: #original_exception is deprecated. Use #cause instead. (called from initialize at /.rvm/gems/ruby-2.3.1@myapp-rails-5.0/gems/better_errors-2.1.1/lib/better_errors/raised_exception.rb:8)

ArgumentError - First argument in form cannot contain nil or be empty:
  actionview (5.0.0.1) lib/action_view/helpers/form_helper.rb:438:in `form_for'
  simple_form (3.3.1) lib/simple_form/action_view_extensions/form_helper.rb:26:in `block in simple_form_for'
  simple_form (3.3.1) lib/simple_form/action_view_extensions/form_helper.rb:45:in `with_simple_form_field_error_proc'
  simple_form (3.3.1) lib/simple_form/action_view_extensions/form_helper.rb:25:in `simple_form_for'
  app/views/devise/invitations/new.html.erb:10:in `_app_views_devise_invitations_new_html_erb__4202866183412601869_70355747934720'
  actionview (5.0.0.1) lib/action_view/template.rb:158:in `block in render'
  activesupport (5.0.0.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (5.0.0.1) lib/action_view/template.rb:348:in `instrument'

```

For this operation, I removed the `binding.pry` from the `InvitationsController#New` for illustration purposes.

**Comment by scambra** [comment]
I don't see your request include email in url (no ?email= in URL and no parameters line below "processing by" line)

Check href in generated html, does it include email parameter?

**Comment by marcamillion** [comment]
You are right, it doesn't include the email parameter in the link. Here is the HTML generated by the above `link_to`:

    <a class="btn btn-xs btn-primary" href="/users/invitation/new">Invite Jeremy Verley</a>

Isn't that a function of the routes for `new_user_invitation_path`? 

Because if I create another link, say this one:

    <%= link_to "Invite #{@profile.name}", invite_path(@profile), method: :post, data: { confirm: "Are you SURE you are ready to invite #{@profile.name}?"}, class: "btn btn-xs btn-primary" %>

Which corresponds to the following path:

    post 'invite/:id', to: 'profiles#invite_user', as: :invite

Then in my `ProfilesController`, I create an `invite_user` action that looks like this:

```ruby
  def invite_user
    User.invite!(email: @profile.email, first_name: @profile.first_name, last_name: @profile.last_name, avatar: @profile.avatar)
  end

```

When I click that link, I get the following log event:

```
Started POST "/invite/jeremy-verley-st-george-s-college" for ::1 at 2016-10-26 23:09:01 -0500
Processing by ProfilesController#invite_user as HTML
  Parameters: {"authenticity_token"=>"rqibD/bh5km9crZv5/UEOwKqf/lAcaB6CkddZWl9HmQ==", "id"=>"jeremy-verley-st-george-s-college"}
  Profile Load (2.0ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."slug" = $1 ORDER BY "profiles"."id" ASC LIMIT $2  [["slug", "jeremy-verley-st-george-s-college"], ["LIMIT", 1]]
  Grade Load (2.2ms)  SELECT "grades".* FROM "grades" WHERE "grades"."profile_id" = 21
  HABTM_Positions Load (1.9ms)  SELECT "positions_profiles".* FROM "positions_profiles" WHERE "positions_profiles"."profile_id" = 21
  Position Load (1.5ms)  SELECT "positions".* FROM "positions" WHERE "positions"."id" IN (2, 3, 4)
  Achievement Load (1.0ms)  SELECT "achievements".* FROM "achievements" WHERE "achievements"."profile_id" = 21
  Video Load (1.8ms)  SELECT "videos".* FROM "videos" WHERE "videos"."profile_id" = 21
  Transcript Load (2.0ms)  SELECT "transcripts".* FROM "transcripts" WHERE "transcripts"."profile_id" = 21
No template found for ProfilesController#invite_user, rendering head :no_content
Completed 204 No Content in 469ms (ActiveRecord: 12.4ms)

```

Notice the params are now correct, as is the `POST` request and everything else that follows.

So it seems to me that the issue is in the routing for the `new_user_invitation_path`.

**Comment by scambra** [comment]
new_user_invitation_path is a route for new action in InvitationsController, new action in restful always is GET request to display form, and that form will make a post request to create action. So probably you wanted post request with email, as you did with invite_path(@profile), method: :post
