### ISSUE TITLE
Wrong invitation_token being sent in email

### ISSUE THREAD

**Issue by godzilla74** [scambra/devise_invitable#697]
It seems like the wrong `invitation_token` is being sent to my new user so that when they attempt to accept the invite the User isn't found:

Here is what is sent to the user:
`http://localhost:3000/users/invitation/accept?invitation_token=z_FxaxVyFZx87tUTwcJ9`

But here is what is in the DB for the user:
```
[16] pry(main)> user.invitation_token
=> "638a92fafd29e394280fac0d0af6e580ec36642405f64df378fb454fffc3c79a"
```

If I use the DB provided token in the url, I don't get an error.

I've tried to use this in my mailer, but that's still sending the incorrect token:

`<p><%= link_to t("devise.mailer.invitation_instructions.accept"), accept_user_invitation_url(:invitation_token => @token) %></p>`

**Comment by scambra** [comment]
token in url is not same as saved in db, because raw token is sent and hash is saved to db, same as devise does for other tokens
