### ISSUE TITLE
unable to add fields to resource.class.invite_key_fields

### ISSUE THREAD

**Issue by clairity** [scambra/devise_invitable#698]
this seems like a (hopefully quick) documentation issue:

how do you add fields to `resource.class.invite_key_fields` for use in the `new.html.erb` template?

it seems designed to allow for it, but it's not obvious how to do so (at least the obvious things i tried didn't work).

**Comment by scambra** [comment]
Define invite_key in devise.rb initializer, invite_key_fields return invite_key.keys

Also, you can define them in model, as parameters for invitable:
devise ..., invitable: {invite_key: {email: Devise.email_regexp}}

**Comment by clairity** [comment]
thanks! i tried both methods successfully (on rails 5.0.1, devise 4.2.0). i had to use this syntax (in case anyone else is confused by this too) to add a `:name` field (for example):

```
config.invite_key = { email: Devise.email_regexp, name: Proc.new { 2..80 } }
```
in `config/initializers/devise.rb`, or
```
devise :database_authenticatable, ... , 
  :invitable, invite_key: { email: Devise.email_regexp, name: Proc.new { 2..80 } }
```
in my User model.

devise only defines `email_regexp` & `password_length` in the `:validatable` module, so it seems that any other field will need to pass in a custom validation as a Proc (as your documentation notes). i was hoping to reuse the validator from my User model but couldn't get that to work.

**Comment by scambra** [comment]
Proc.new { 2..80 } doesn't make sense there, it always return true
proc === value, calls proc with value as argument, and Proc.new { 2..80 } return 2..80 which is always true.

You would want one of these:
Proc.new { |v| (2..80).include? v.size }
Proc.new { |v| (2..80) === v.size }
/.{2,80}/

**Comment by clairity** [comment]
ah yes, thank you. i was in too big of a hurry to get that wrapped up. 😀
