### ISSUE TITLE
Allowing custom invite messages when having two different Devise User-like models

### ISSUE THREAD

**Issue by alopez25** [scambra/devise_invitable#700]
Scambra, I realised you may be quite busy but would really appreciate your help since I haven't been able to figure out how to make this work. 

I have 2 user-like models in my app: 'Participant' and 'Member'. I'm trying to allow them to include a custom message when they invite other members/participants. 
I'm following your  [tutorial](https://github.com/scambra/devise_invitable/wiki/Customizing-for-different-Invite-use-cases-(emails-etc.)#allowing-users-to-create-a-custom-invite-message) and trying to override invitation_controller.rb as suggested so I've created two sets of controllers: one on `controllers/participants/invitations_controller.rb` and the other in `controllers/members/invitations_controller.rb`. 

Unfortunately, I don't seem to be able to override devise invitations controller. When using pry inside my create method seems that these custom controllers go untouched when sending an invite. What am I doing wrong?

PS.

I've also included a mailer at `mailers/notification_mailer.rb` as suggested, but when sending an invitation `devise_invitable-1.7.1/app/views/devise/mailer/invitation_instructions.html.erb` is still used to send the email and not the new custom mailer.

Below an example of the code I've used in the controller for participants.

**controllers/participants/invitations_controller.rb**
```
class Participants::InvitationsController < Devise::InvitationsController
      before_action :update_sanitized_params, only: :update

  def create
    binding.pry
    @from    = params[:from]
    @subject = params[:invite_subject]
    @content = params[:invite_content]

    @participant = Participant.invite!(params[:user], current_member) do |u| #XXX Check if :user should be changed
      u.skip_invitation = true
    end

    ParticipantInvitationNotificationMailer.invite_message(@participant, @from, @subject, @content).deliver if @participant.errors.empty?
    @participant.invitation_sent_at = Time.now.utc # mark invitation as delivered

    if @participant.errors.empty?
      flash[:notice] = "successfully sent invite to #{@participant.email}"
      respond_with @participant, :location => root_path
    else
      render :new
    end
  end
end
```

**Comment by scambra** [comment]
Controller looks right, have you changed your routes?
https://github.com/scambra/devise_invitable#configuring-controllers

**Comment by alopez25** [comment]
Yes I've modified my routes as specified in the documentation.

My custom controllers are in:
```
controllers/participants/invitations_controller.rb
controllers/members/invitations_controller.rb
```

I modified my routes as below:

`devise_for :members, controllers: { invitations: "members/invitations" }
  devise_for :participants, controllers: { invitations: "participants/invitations" }
`

Bellow a portion of the routes output (only showing Participant related for brevity):

```
    cancel_participant_registration GET    /participants/cancel(.:format)                                       devise_invitable/registrations#cancel
       new_participant_registration GET    /participants/sign_up(.:format)                                      devise_invitable/registrations#new
      edit_participant_registration GET    /participants/edit(.:format)                                         devise_invitable/registrations#edit
           participant_registration PATCH  /participants(.:format)                                              devise_invitable/registrations#update
                                    PUT    /participants(.:format)                                              devise_invitable/registrations#update
                                    DELETE /participants(.:format)                                              devise_invitable/registrations#destroy
                                    POST   /participants(.:format)                                              devise_invitable/registrations#create
      accept_participant_invitation GET    /participants/invitation/accept(.:format)                            participants/invitations#edit
      remove_participant_invitation GET    /participants/invitation/remove(.:format)                            participants/invitations#destroy
         new_participant_invitation GET    /participants/invitation/new(.:format)                               participants/invitations#new
             participant_invitation PATCH  /participants/invitation(.:format)                                   participants/invitations#update
                                    PUT    /participants/invitation(.:format)                                   participants/invitations#update
                                    POST   /participants/invitation(.:format)                                   participants/invitations#create
```

Strangely, I have sanitised a :username and the 'Update' method  in the same controller gets  touched when a user confirms the invitation by setting a password.

Or perhaps I'm not getting it right. I'm assuming that the 'Create' method will be called when creating an invitation via something like...

`Participant.invite!({:email => @invitation_draft.email}, current_member)`

Am I correct? Again your help would be highly appreciated.

**Comment by scambra** [comment]
create controller method is called when user loads new and send form, create method in controller call Participant.invite! which create participant record.

When sending form, you should see in log create request:
Started POST "/participants/invitation" ...
Processing by Participants::InvitationsController#create as HTML

**Comment by alopez25** [comment]
I see, I was quite confused then as calling Participant.invite! triggered the Mailer as well. Anyway it make sense now. I'll adapt my code accordingly. Thanks a lot for your help!
