### ISSUE TITLE
Completed 401 Unauthorized, when invite user

### ISSUE THREAD

**Issue by alokrawat050** [scambra/devise_invitable#706]
I am developing a SAAS app.
I used the Apartment,Devise and Devise Invitable gem.
Problem is,after successfully sign-in , when i'm going to invite a user then it redirect to sign-in page.

Below is the details
```
gem 'devise', '~> 4.2'
gem 'devise_invitable', '~> 1.7.1'
```

here is my routes.rb,
```
devise_for :users
resources :users, only: :index
```

in applicationcontroller.rb,
`before_filter :load_schema, :authenticate_user!`
```
def load_schema
      Apartment::Tenant.switch!('public')
      return unless get_subdomain_acc.present?      
      if current_account
        Apartment::Tenant.switch!(current_account.company_name)
      else
        redirect_to root_url(subdomain: false)
      end
end
```

in user.rb model,
`devise :invitable, :database_authenticatable, :registerable, :authentication_keys => [:login]`

in my index.html.rb file,
```
<%= form_for(User.new, url: user_invitation_path, html: { class: "form-inline" }) do | f |  %>
                <%= f.email_field :email, placeholder: 'Email', label: false, class: "form-control" %>
                <%= f.submit("Invite User", class:"btn btn-primary", data: {:confirm => msg('Invite User'), :disable_with => 'Invite User'}) %>
            <% end %>
```

below is the server log,
Started POST "/users/invitation" for 60.32.149.128 at 2017-03-24 01:05:55 +0000
Cannot render console from 60.32.149.128! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Devise::InvitationsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"xHl+ADZ70UOrDe/NowFNdMAxY6e/ObcK14Wy9kawqzShTsm4JgZET6tD6774XrCuODPxGyV9omXRsCALUYmCmg==", "user"=>{"email"=>"abc@gmail.com"}, "commit"=>"Invite User"}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
Completed 401 Unauthorized in 3ms (ActiveRecord: 0.3ms)

Started GET "/users/sign_in" for 60.32.149.128 at 2017-03-24 01:05:56 +0000
Cannot render console from 60.32.149.128! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Devise::SessionsController#new as HTML
  CompanyMaster Load (0.3ms)  SELECT  "public"."company_masters".* FROM "public"."company_masters" WHERE "public"."company_masters"."company_name" = $1 LIMIT 1  [["company_name", "abc"]]
  Rendered devise/shared/_links.html.erb (4.0ms)
  Rendered devise/sessions/new.html.erb within layouts/application (10.3ms)
Completed 200 OK in 93ms (Views: 89.6ms | ActiveRecord: 1.3ms)

is something i did wrong or missed?
Thanks in advance.

**Comment by jayelkaake** [comment]
Same issue for me here using:
```
gem 'devise', '~> 3.5.3'
gem 'devise_lastseenable', '~> 0.0.6'
gem 'devise_invitable', '~> 1.6.1'
```

**Comment by jayelkaake** [comment]
The method on your form should be `PUT` not `POST` (`POST` is default).  As a result it's going to the wrong controller action. I ran into the same issue.

Update your form HTML code to this and it should work:
```ruby
<%= form_for(User.new, url: user_invitation_path, html: { class: "form-inline", method: :put }) do | f |  %>
```

**Comment by scambra** [comment]
@jayelkaake it's trying to create new invitation, method is post for that action, it's going to right action Devise::InvitationsController#create

I guess is failing authentication for authenticate_inviter! before action (added with prepend_before_action). Not sure if changing load_schema to prepend_before_action would fix issue. If prepend_before_action doesn't work, you could try to override authenticate_inviter to call load_schema and then super:
https://github.com/scambra/devise_invitable#controller-filter

Although, best way would be use middleware for apartment instead of before_filter:
https://github.com/influitive/apartment#switching-tenants-per-request

**Comment by jayelkaake** [comment]
Oh yeah you're right, misread his message.

**Comment by alokrawat050** [comment]
thanks, @jayelkaake 
when I changed it to PUT, but did not work. It redirect to a sign-up page and used update method. I think, it should be use create method.
Started PUT "/users/invitation" for 60.32.149.128 at 2017-03-27 02:59:50 +0000
Cannot render console from 60.32.149.128! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Users::InvitationsController#update as HTML
below is the modified code.

```
<%= simple_form_for(User.new, url: user_invitation_path, html: { class: "form-inline", method: :post }) do | f |  %>
```
in my application controller.rb file,
```
def after_invite_path_for(resource)
      users_path
    end
```

**Comment by alokrawat050** [comment]
@scambra thanks.
The second link solution is perfect.it's wokring for me.
```
Although, best way would be use middleware for apartment instead of before_filter:
https://github.com/influitive/apartment#switching-tenants-per-request
```

below is the modified details.
1. in application.rb file,
`require 'apartment/elevators/subdomain'`

`config.middleware.use 'Apartment::Elevators::Subdomain'`

in index.html.rb file,
```
<%= simple_form_for(User.new, url: user_invitation_path, html: { class: "form-inline", method: :post }) do | f |  %>
                <%= f.input :email, placeholder: 'Email', label: false, class: "form-control" %>
                <%= f.button :submit, 'Invite User', class:"btn btn-primary" %>
            <% end %>
```

thanks a lot.
