### ISSUE TITLE
Could not find generator 'devise_invitable:install'

### ISSUE THREAD

**Issue by spchetan11** [scambra/devise_invitable#713]
I'm trying to setup scambra devise_invitable in my rails 5 project. After setting up the gem and bundle install, When I run the first command for the initial setup -
`rails generate devise_invitable:install` I get the following error.

```
Expected boolean default value for '--markerb'; got :erb (string)
Could not find generator 'devise_invitable:install'.
Maybe you meant 'devise:install', 'annotate:install' or 'responders:install'
```
This is my gemfile.

```
gem 'devise', github: 'plataformatec/devise', branch: 'master'
gem 'devise_invitable', '~> 1.7.2'
```
How do I fix this?

**Comment by spchetan11** [comment]
Okay. Restarted me laptop and it worked. Just like the other user did who was facing the same issue.

**Comment by nezirz** [comment]
I tried with restarting and not worked in my case ruby 2.5.1 rails 5.2.3 dell xps ubuntu 18.04.
What worked is:

`bundle exec gem install devise_invitable`

then I saw that it installed version:

```
Successfully installed devise_invitable-2.0.1
Parsing documentation for devise_invitable-2.0.1
Done installing documentation for devise_invitable after 0 seconds
1 gem installed 
```

so I updated Gemfile line to correct version:
`gem 'devise_invitable', '~> 2.0.1'`

and then run `rails generate devise_invitable user `successfully!
