### ISSUE TITLE
Validation problem

### ISSUE THREAD

**Issue by GarPit** [scambra/devise_invitable#719]
It saves record with `save(validates: false)` but model has `errors` not blank after this and action `create` keeps rendering `new` view instead of redirecting to `after_invite_path_for`

**Comment by GarPit** [comment]
I think maybe better to have

    resource_invited = resource.persisted?

**Comment by scambra** [comment]
If you want to validate record when is invited, enable validate_on_invite, it will run invitable.valid? (inside invite! class method)

**Comment by scambra** [comment]
If validate_on_invite is disabled, errors must be empty, unless is trying to invite with an email which already exists. In that case invite_resource will return existing record (which is persisted) with errors. That's why errors.empty? must be used instead of resource.persisted?

**Comment by GarPit** [comment]
`validate_on_invite` disabled, but errors not empty

**Comment by GarPit** [comment]
# Flag that force a record to be valid before being actually invited
    # Default: false
    # config.validate_on_invite = true

**Comment by scambra** [comment]
so, what errors do you get? with validate_on_invite disabled you should get errors only in invite key fields, taken error if record existed, invalid if record doesn't exist and value doesn't match with regexp.

Default invite keys and regexps:
invite_key = {:email => Devise.email_regexp}

**Comment by GarPit** [comment]
Ok, let's say I have some fields in User model need to be validates in regular case. But they should not be validated in case of invitation. Is this the case your gem could handle out of the box?

**Comment by scambra** [comment]
If you don't want to run any validation in case of invitation, only email with regexp on invite_key, it works out of the box.

If you want to run validations, you have to enable validate_on_invite. If any validation mustn't run in case of invitation, add :if => :accepted_or_not_invited? to validation

**Comment by GarPit** [comment]
Thanks for this, this could be mentioned in docs - `accepted_or_not_invited?` condition
