### ISSUE TITLE
Unable to accept an invitation

### ISSUE THREAD

**Issue by danielwestendorf** [scambra/devise_invitable#722]
I'm having trouble accepting invitations for a user. I'm seeing a number of these types of issues, so this may be a bigger problem -- or maybe just a configuration problem after upgrading? This is what I've found:

```
devise (4.3.0)
devise_invitable (1.7.2)
```

1. `User.last.invite!`. This creates a new user and sends the invitation email.
2. Invitation email generates a URL such as this http://localhost:3000/users/invitation/accept?invitation_token=4wUJqa-F_srkgSc_JwFc
  a. At this point, the user record in the database has a hashed `invitation_token` like `6835debac082a389136449b5ddddd9ef166df06ab7c10a6d4940bf1515fc3e47`
3. Visiting the `accept_invitation_url` prompts to set a password 🎉 
4. Clicking submit renders the error `Invitation token is invalid` 😢 
  a. At this point, the user record in the database has an updated `invitation_token` field which matches the raw token of `4wUJqa-F_srkgSc_JwFc`. WHAT!?!?!?

What's going on here?

**Comment by scambra** [comment]
Can you send a pull request with failing test?

**Comment by danielwestendorf** [comment]
I think I've sorted out what cause of the problem is here.

Within my application controller, I have a `before_action` which only fires for devise controllers. This method updates the timezone for the current resource. Why the `invitation_token` gets overwritten is because of an update call made within this action where the `invitation_token` has been set to the `raw_invitation_token`.

This boils down to setting the `invitation_token` as the raw value in a [#edit](https://github.com/scambra/devise_invitable/blob/master/app/controllers/devise/invitations_controller.rb#L42) and being accepted as an permitted attribute in the [#update](https://github.com/scambra/devise_invitable/blob/master/app/controllers/devise/invitations_controller.rb#L84) action's [parameters](https://github.com/scambra/devise_invitable/blob/master/lib/devise_invitable/parameter_sanitizer.rb#L25).

The fault of this on me for updating a record on a GET when it has unpersisted changes, however, I wouldn't expect these values to be set by a GET either.

Closing.
