### ISSUE TITLE
Invitation token given in invitation link isn't attached to a user

### ISSUE THREAD

**Issue by L33tH4x0r** [scambra/devise_invitable#723]
I'm using a multi tenant application and when some of the users try to accept their invitations and set their passwords, they are unable to do so because the invitation token cant find their record. I modified the invitations controller as follows
```
def create
    # DEIVSE CONTROLLER CODE
    self.resource = invite_resource
    resource_invited = resource.errors.empty?

    yield resource if block_given?

    if resource_invited
    ## AFTER DEVISE CONTROLLER CODE
    User.add_invited_user(params[:user])

    # END CUSTOM CODE
      if is_flashing_format? && self.resource.invitation_sent_at
        set_flash_message :notice, :send_instructions, :email => self.resource.email
      end
      if self.method(:after_invite_path_for).arity == 1
        respond_with resource, :location => after_invite_path_for(current_inviter)
      else
        respond_with resource, :location => after_invite_path_for(current_inviter, resource)
      end
    else
      respond_with_navigational(resource) { render :new }
    end
  end

  # this is called when accepting invitation
  # should return an instance of resource class
  def accept_resource
    resource = resource_class.accept_invitation!(update_resource_params)
    ahoy.track("Invitation accepted")
    resource
  end
  private

  def resource_params
    params.require(:user).permit(:name, :email,:invitation_token, :first_name, :last_name)
  end

  def resource_from_invitation_token
    if User.count == 0
      Apartment::Tenant.switch!('public')
      Apartment::Tenant.switch!(request.subdomain)
    end
    # TODO this may be the issue
    unless params[:invitation_token] && self.resource == resource_class.find_by_invitation_token(params[:invitation_token], true)
      flash[:error] = "Something went wrong, please click the link in your email again. Else, contact support at support@"
      puts "Error #0001: Invitation Token Error"
      redirect_to after_sign_out_path_for(resource_name)
    end
  end
````
When the invite fails, the user gets the flash error mentioned in the resource_from_invitation_token.

We are using the following configuration:
Ruby: 2.3.4
Rails: 5.0.1
Apartment: 1.0.2
Postgres

**Comment by scambra** [comment]
Your custom code changed this line:

https://github.com/scambra/devise_invitable/blob/master/app/controllers/devise/invitations_controller.rb#L100

DeviseInvitable code has self.resource = resource_class.find_by_invitation_token, but you changed to compare instead of assign

**Comment by L33tH4x0r** [comment]
We changed that back, but it was breaking before we had the comparison operator there. When things were failing it was using the assignment operator on `self.resource`

**Comment by scambra** [comment]
As you are using multi-tenant, and I don't know of any other issue accepting invitations (and tests are passing), please log and ensure right database is being used

**Comment by L33tH4x0r** [comment]
So we figured it out. Had to do with another function that we were using that gave an admin a list of all their users that hadn't accepted their invitations. We gave them a link that they could send to the users to let them into the site. Unfortunately, this invalidates the previous invitation  the got on signup.

This brings up another separate question, is there a way to just get the invitation link without invalidating the previous one?

**Comment by scambra** [comment]
No, because devise saves a hash of actual token in db, resending invitation needs to generate a new one.
Changing to save each invitation in new table, instead of creating new users, as requested with #228 and #388 would allow to have multiple invitations working. However I don't have time to do this change now.
