### ISSUE TITLE
How to allow user to access account when invitation hasn't been accepted?

### ISSUE THREAD

**Issue by jkostolansky** [scambra/devise_invitable#725]
I'm creating an app, where User has some required fields (name, TOS, ...) and I have a problem with the following scenario:

1. Someone invites a user to the app
2. The user doesn't click on the invitation link
3. After some time, the user wants to sign up (invitation link is now invalid). The app tells him "email has already been taken".
4. The user requests a password reset, clicks on the link, fill-in new password, but "name can't be blank" etc.

What is the proper way to allow this user to set up the new account?

**Comment by scambra** [comment]
Step 3 shouldn't happen, devise invitable changes registrations controller to DeviseInvitable::RegistrationsController, which allows to register to invited users.

Are you using devise registrations controller or your own controller instead of devise invitable controller?

**Comment by jkostolansky** [comment]
Thanks, I was using generated controllers (`rails generate devise:controllers`). Now I have bigger problem:

1. Someone invites a user to the app
2. The user doesn't click on the invitation link
3. The user on the sign-up page fills in email (leaving other fields blank) and clicks Sign up
3. There are some validation errors (name can't be blank, password can't be blank, ...) BUT an email with a confirmation link is sent.

**Comment by jkostolansky** [comment]
Ok, I fixed it with my own registration controller:
```ruby
def create
  build_resource(sign_up_params)

  resource_saved = resource.save
  yield resource if block_given?
  if resource_saved
    # workaround for invited user
    if resource.respond_to?(:invited_to_sign_up?) && resource.invited_to_sign_up?
      resource.send_confirmation_instructions if resource.confirmation_required_for_invited?
      resource.accept_invitation
      resource.save
    end
    # normal flow
    if resource.active_for_authentication?
      set_flash_message! :notice, :signed_up
      sign_up(resource_name, resource)
      respond_with resource, location: after_sign_up_path_for(resource)
    else
      set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
      expire_data_after_sign_in!
      respond_with resource, location: after_inactive_sign_up_path_for(resource)
    end
  else
    clean_up_passwords resource
    set_minimum_password_length
    respond_with resource
  end
end

protected

def build_resource(hash=nil)
  hash ||= {}
  if hash[:email].present?
    self.resource = resource_class.find_by_email(hash[:email])
    if self.resource && self.resource.respond_to?(:invited_to_sign_up?) && self.resource.invited_to_sign_up?
      self.resource.attributes = hash
    else
      self.resource = nil
    end
  end
  self.resource ||= super
end
```

And I also need to specify `method: :post` for the registration form to properly handle the URL for an existing record. It seems to work.

**Comment by scambra** [comment]
Nice to hear that

**Comment by rubendinho** [comment]
I'm having a similar problem as the OP, but I am confused about how updating the RegistrationsController solves the Step 3 problem, which is caused by the Devise PasswordsController. Per below, the user will be sent password reset instructions whether she has accepted the invitation or not. 

```
  # POST /resource/password
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with({}, location: after_sending_reset_password_instructions_path_for(resource_name))
    else
      respond_with(resource)
    end
  end
```

**Comment by jkostolansky** [comment]
Just override the method, something like this:

```ruby
class Users::PasswordsController < Devise::PasswordsController
  # POST /resource/password
  def create
    # disable password reset for invited users
    resource = resource_class.find_or_initialize_with_errors(Devise.reset_password_keys, resource_params, :not_found)
    if resource && resource.respond_to?(:invited_to_sign_up?) && resource.invited_to_sign_up?
      set_flash_message :alert, :invited
      respond_with({}, location: new_registration_path(resource_name))
    else
      super
    end
  end
end
```

**Comment by rubendinho** [comment]
@jkostolansky very helpful - thanks.
