### ISSUE TITLE
invitation_due_at doesn't work when sent in background job (Sidekiq)

### ISSUE THREAD

**Issue by jaredSiebert** [scambra/devise_invitable#730]
Environment:
macOS 10.13.2
Ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
Rails 5.1.4
devise (4.3.0)
devise_invitable (1.7.2)
sidekiq (5.0.5)

Devise is setup to send emails through Sidekiq (and they send fine) by adding the following to my User model as outlined here https://github.com/plataformatec/devise#activejob-integration

```
def send_devise_notification(notification, *args)
  devise_mailer.send(notification, self, *args).deliver_later
end
```
With `send_devise_notification` commented out, the invitation emails send fine, but with it, the invitation emails error out in Sidekiq with the following
```
2017-12-19T19:14:33.476Z 12539 TID-owzud7kok WARN: ActionView::Template::Error: undefined method `+' for nil:NilClass
2017-12-19T19:14:33.476Z 12539 TID-owzud7kok WARN: /Users/jaredsiebert/.rvm/gems/ruby-2.4.2/gems/devise_invitable-1.7.2/lib/devise_invitable/model.rb:212:in `invitation_due_at'
/app/views/devise/mailer/invitation_instructions.html.erb:7:in `_app_views_devise_mailer_invitation_instructions_html_erb___1398191856332147584_70292319516100'
```

The code it's complaining about is `invitation_due_at`
```
<% if @resource.invitation_due_at %>
  <p><%= t("devise.mailer.invitation_instructions.accept_until", due_date: l(@resource.invitation_due_at, format: :'devise.mailer.invitation_instructions.accept_until_format')) %></p>
<% end %>
```
Once removed, Sidekiq can send the emails without issue. 

What's changing with `@resource.invitation_due_at` when sent through Sidekiq? The other @resource references work fine, just not `invitation_due_at`

**Comment by scambra** [comment]
error is in second line of this code (from invitation_due_at method):

```ruby
        time = self.invitation_created_at || self.invitation_sent_at
        time + self.class.invite_for
```

invitation_created_at is set in invite! method, before saving invitable record, in this line:
https://github.com/scambra/devise_invitable/blob/master/lib/devise_invitable/model.rb#L143

Can you post sql saving invited user, both with send_devise_notification override and without it?
Also, you could add to log "self" in send_devise_notification, invitation_created_at should be set.

**Comment by jaredSiebert** [comment]
Well, this is slightly embarrassing... I was running the invite! command from console, but was in sandbox mode from earlier testing :/
