### ISSUE TITLE
Effect of validate_on_invite

### ISSUE THREAD

**Issue by ikneg** [scambra/devise_invitable#731]
For `validate_on_invite`, it is described in documents as follows.
`validate_on_invite: force a record to be valid before being actually invited.`

I want to understand about it exactly.

I understand that the following are their behaviors. Does this correct?
`:validate_on_invite => true` Until the user receives the mail and sets the password, the user record is not created.
`:validate_on_invite => false` A user record is created when sending an invite mail to the user

**Comment by scambra** [comment]
No, user is always created when invitation is sent. validate_on_invite will run validations when invitation is sent, so invite form must include all required attributes. Default is not to validate on invite, and validate when accepting invitation, so invite form only has email, and accept invitation form must have all other required attributes
