### ISSUE TITLE
User invitations randomly fail

### ISSUE THREAD

**Issue by L33tH4x0r** [scambra/devise_invitable#739]
Hey there!

We are running devise invitable on a growing database and we notice that user invitations will randomly fail on them. We built a page that will generate a new invitation when that happens, but I am a little stuck on figuring out how to debug this. This error occurs when a newly generated user tries to accept their invitation, so I know that they aren't expired. Also, it doesn't happen to every user which I find strange.

What typically happens is that a user is sent an invitation, that includes their user id and their `invitation_token`, the controller goes to `Users::InvitationController` and immediately gets redirected to the `resource_from_invitation_token` action. The invitation token goes through the `find_by_invitation_token` action and the hash can't find a user and it subsequently fails.

Any ideas on where to start looking to fix this issue?

**Comment by scambra** [comment]
As only fails randomly, I guess raw token is sent. Other people had issues on multi-tenant apps, or calling update on before action (https://github.com/scambra/devise_invitable/issues/722)

**Comment by L33tH4x0r** [comment]
I noticed that I left a comment on another issue #502 so I took your recommendation there and added various other debugging logs throughout the invitation process. I am also going to be viewing the PostgreSQL logs as I accept invitations from various email providers to see if I can get one to fail.

**Comment by L33tH4x0r** [comment]
We found the issue! It has to do with the Rack hierarchy and Warden being placed above our subschema gem, Apartment. If you are using the Apartment Gem, then you need to force Apartment to be above Warden in your `config/application.rb` file and add the following code:
`Rails.application.config.middleware.insert_before "Warden::Manager", Apartment::Elevators::Subdomain`

Read more about custom elevators here: [https://github.com/influitive/apartment#custom-elevator](url)
