### ISSUE TITLE
it does not do url decode if invitation_token parameter is decoded 

### ISSUE THREAD

**Issue by KMadhuSudhan** [scambra/devise_invitable#750]
There is feature in my application, where admin will be sending invitation to users . 
When an admin sent invitation to user via email, user will be receiving email with list of  instructions ,along with this an invitation link also will be sent to login and access my application .When user clicks on invitation link from sent mail , Some times i am getting decoded url .please  see following two request one with decode URL and another one without decoded url. Following requests are captured from rails logs

**URL Request with  Deocded:** 
Started GET "/users/invitation/acceptinvitation_token%3DjceB8Tn6pYNmRFYozbPq&source=gmail&ust=1511353971734000&usg=AFQjCNFyNX7aGiRhETG7EJ1MCiru4kfYoA" for 127.0.0.1 at 2017-11-21 18:08:15 +0530
Processing by Users::InvitationsController#edit as HTML
  Parameters: {"invitation_token=jceB8Tn6pYNmRFYozbPq"=>nil, "source"=>"gmail", "ust"=>"1511353971734000", "usg"=>"AFQjCNFyNX7aGiRhETG7EJ1MCiru4kfYoA"}

in this case invitation_token param and invitation_token value getting merged . 
invitation_token param , invitation_token param values are not able to identify and user getting invalidated 

**URL Request with out decode:** 

Started GET "/users/invitation/accept?invitation_token=jceB8Tn6pYNmRFYozbPq" for ::1 at 2017-11-21 18:23:53 +0530
Processing by Users::InvitationsController#edit as HTML
  Parameters: {"invitation_token"=>"jceB8Tn6pYNmRFYozbPq"}

In this case its works without no issues .

**Comment by scambra** [comment]
First url is wrong, nothing related to decoding or encoding. It's missing question mark between accept and invitation_token.

Check your email

**Comment by KMadhuSudhan** [comment]
This is the request has received from email

**Comment by scambra** [comment]
If your email has a url like that, then email is wrong
I don't know why you have emails with right url and wrong one, but I guess you changed your mail template, because I see more params in first url

**Comment by KMadhuSudhan** [comment]
my email content  is right only i am sending plain text and link also as in plain text . while opening link gmail is doing url encode or browser doing url encode .
please below logic for forming email link 
raw, enc = Devise.token_generator.generate(User, :invitation_token)
invitation_link =  host_url + accept_user_invitation_path(invitation_token: raw)

**Comment by scambra** [comment]
Then it isn't poblem of devise invitable, it's email viewer which doesn't display link correctly, it wouldn't happen with html email. Also, you can try to shorten url, using some web service, or using shortener gem:
https://github.com/jpmcgrath/shortener

**Comment by KMadhuSudhan** [comment]
can pls understand problem and close it, there is a issue with this thats why i reported

**Comment by scambra** [comment]
I understand problem, your email is right but gmail is breaking url. There is nothing I can do, it will happen with other urls too. Easier way to avoid this is using html mail, because url can be href attribute and it won't break
