### ISSUE TITLE
before_validation :on => create  fails to work on invitation

### ISSUE THREAD

**Issue by gullhead** [scambra/devise_invitable#759]
Hi, 
I'm trying to set up account and role in my model 

```
class User < ApplicationRecord
  before_validation :setup_role,    on: :create
  before_validation :setup_account, on: :create
```

These callbacks are not getting invoked when new User with an invitation token is created. Is it bug or a feature?

**Comment by scambra** [comment]
feature, if you want to run validations on invite, you must enable them with validate_on_invite setting
https://github.com/scambra/devise_invitable#model-configuration

**Comment by gullhead** [comment]
Ok, thx!
