### ISSUE TITLE
Is there a callback for when the invite is updated?

### ISSUE THREAD

**Issue by krue-doug** [scambra/devise_invitable#763]
If the same email is invited by multiple people, it seems to just update the record and completely negate the previous invite. Is there a callback for when the invitation is updated? Is there a way to still honor the previous invite? For example, if a person is invited by 2 users then the person should be able to accept either invite and it would credit the user based on the invite that the person chose.

**Comment by scambra** [comment]
To support this, we need to keep track of every invitation in new table, it will be related to these 2 open issues: #228 and #388. It's a big change which I don't have time to do now, but I will review a pull request implementing it and give hints if issues are found

**Comment by scambra** [comment]
About callbacks, there are before_invitation_created and after_invitation_created callbacks, token is already changed when before_invitation_created is called, but other invitation fields are not changed yet. after_invitation_created callback is called after saving attributes to database and invitation email is sent
