### ISSUE TITLE
Is it possible to accept an invite via API only?

### ISSUE THREAD

**Issue by krue-doug** [scambra/devise_invitable#764]
This would be helpful for mobile apps and web apps. I can overwrite the method, but what are the implications of removing the authenticity token support? If we can rely on the invite token being semi-private because it's only accessible by the person receiving the email then removing the authenticity token should be fine, but I want a sanity check.

**Comment by scambra** [comment]
Token can't be get from db because db saves a hash of token sent by email, only way to steal token is get access to email or intercept mail traffic between smtp servers

**Comment by krue-doug** [comment]
@scambra Okay, good to hear. 

This is what I ended up with.

Added this in devise.rb:
```
config.navigational_formats = ['*/*', :json, :html]
```

Overwriting controller:
```
class Users::InvitationsController < Devise::InvitationsController

  skip_before_action :verify_authenticity_token, only: [ :update ]

  def update
    super do |resource|
      if request.format == 'json'
        if resource.errors.empty?
          return respond_with_navigational(resource, status: :success) {
             render json: resource
          }
        else
          return respond_with_navigational(resource)
        end
      end
    end
  end
end
```

**Comment by jamesdixon** [comment]
Useful article on the topic: https://www.codementor.io/@gowiem/deviseinvitable-rails-api-9wzmbisus
