### ISSUE TITLE
How can I access extra options in mailer?

### ISSUE THREAD

**Issue by ccoeder** [scambra/devise_invitable#773]
Hi,

I want to add a redirect_url param to accept_invitation_url, how can I do that?

Basically this is default url: `http://localhost:3000/auth/invitation/accept?invitation_token=1Yx9TDoN-Z_dDvXPJ6Ad`

What I want is: `http://localhost:3000/auth/invitation/accept?invitation_token=1Yx9TDoN-Z_dDvXPJ6Ad&redirect_url=http://google.com`

By the way redirect_url comes from client. Example json:

```
{
	"user": {
		"email": "email@email.com", 
		"name": "User-1",
                 "redirect_url": "http://google.com"
	}
}

```

Thank you!

**Comment by scambra** [comment]
User.invite!(invite_params, current_user, {redirect_url: "http://google.com"}) is setting options = {redirect_url: "http://google.com"}. options is pass to mailer, so you have to create custom mailer (see devise wiki for instructions) and change this method:

```ruby
def invitation_instructions(record, token, opts={})
   @token = token
   @redirect_url = opts[:redirect_url]
   devise_mail(record, :invitation_instructions, opts)
end
```

Then you can use @redirect_url in your mailer view.

Another way it's  adding attr_accessor to model User, and set from controller, so you can access with @resource.redirect_url.:

```ruby
class User < ActiveRecord::Base
  attr_accessor :redirect_url
end

# from controller
@user = User.invite!(invite_params, current_user) do |user|
  user.redirect_url = "http://google.com"
end
```

**Comment by ccoeder** [comment]
It works, thank you!

**Comment by ccoeder** [comment]
I didn't see that before, they are all described here: https://github.com/scambra/devise_invitable/wiki/Customizing-for-different-Invite-use-cases-(emails-etc.)

Sorry to bother you 😞
