### ISSUE TITLE
Login user automatically after invitation accept

### ISSUE THREAD

**Issue by apextemple** [scambra/devise_invitable#779]
I tried to add `super` and `sign_in(params[:user])` to the update method, but nothing seems to work. I wanted to automatically sign_in the user (without a password) and redirect the user to the dashboard.

```
  def update
    if User.accept_invitation!(update_resource_params)
      super
      redirect_to dashboard_path
    else
      redirect_to root_path
    end
  end
```

**Comment by scambra** [comment]
You only have to enable allow_insecure_sign_in_after_accept config option
