### ISSUE TITLE
French translation (fr:)

### ISSUE THREAD

**Issue by frasermayfield** [scambra/devise_invitable#780]
I have been using Devise Invitable for my site and have translated it into multiple languages. It would be great if you could incorporate this into the code for others be able to use.

As a start the following is the translation into french (:fr)

fr:
  devise:
    failure:
      invited: "Vous avez une invitation en attente, acceptez-la pour terminer la création de votre compte."
    invitations:
      send_instructions: "Un e-mail d'invitation a été envoyé à %{email}."
      invitation_token_invalid: "Le jeton d'invitation fourni n'est pas valide!"
      updated: "Votre mot de passe a été défini avec succès. Vous êtes maintenant inscrit."
      updated_not_active: "Votre mot de passe a été défini avec succès."
      no_invitations_remaining: "No invitations remaining"
      invitation_removed: "Aucune invitation restante"
      new:
        header: "Envoyer une invitation"
        submit_button: "Envoyer une invitation"
      edit:
        header: Définir votre mot de passe
        submit_button: Définir mon mot de passe
    mailer:
      invitation_instructions:
        subject: "Instructions d'invitation"
       hello: "Bonjour %{email}"
        someone_invited_you: "Quelqu'un vous a invité à %{url}, vous pouvez l'accepter via le lien ci-dessous."
        accept: "Accepter l'invitation"
        accept_until: "Cette invitation expirera le %{due_date}."
        ignore: "Si vous ne souhaitez pas accepter l'invitation, veuillez ignorer cet e-mail.<br />\nVotre compte ne sera pas créé avant d'avoir accédé au lien ci-dessus et d'avoir défini votre mot de passe."
  time:
    formats:
      devise:
        mailer:
          invitation_instructions:
            accept_until_format: "%B %d, %Y %I:%M %p"

**Comment by scambra** [comment]
Devise doesn't include translations, and I do the same, you can add them to wiki:
https://github.com/scambra/devise_invitable/wiki/I18n
