### ISSUE TITLE
Hindi Translation (hi:)

### ISSUE THREAD

**Issue by frasermayfield** [scambra/devise_invitable#781]
Translation of Devise Invitable into Hindi:

hi:
  devise:
    failure:
      invited: "आपके पास एक लंबित आमंत्रण है, अपना खाता बनाना पूरा करने के लिए इसे स्वीकार करें।"
    invitations:
      send_instructions: "एक निमंत्रण ईमेल %{email} पर भेजा गया है।"
      invitation_token_invalid: "प्रदान किया गया निमंत्रण टोकन मान्य नहीं है!"
      updated: "आपका पासवर्ड सफलतापूर्वक सेट कर दिया गया था। अब आप साइन इन हैं"
      updated_not_active: "आपका पासवर्ड सफलतापूर्वक सेट कर दिया गया था।"
      no_invitations_remaining: "कोई निमंत्रण शेष नहीं है"
      invitation_removed: "आपका निमंत्रण हटा दिया गया था"
      new:
        header: "निमंत्रण भेजें"
        submit_button: "एक निमंत्रण भेजें"
      edit:
        header: "अपना पासवर्ड सेट करें"
        submit_button: "मेरा पासवर्ड सेट करें"
    mailer:
      invitation_instructions:
        subject: "निमंत्रण के निर्देश"
        hello: "नमस्ते %{email}"
        someone_invited_you: "किसी ने आपको %{url} पर आमंत्रित किया है, आप इसे नीचे दिए गए लिंक के माध्यम से स्वीकार कर सकते हैं।"
        accept: "निमंत्रण स्वीकार करें"
        accept_until: "यह आमंत्रण %{due_date} पर समाप्त हो जाएगा"
        ignore: "यदि आप निमंत्रण स्वीकार नहीं करना चाहते हैं, तो कृपया इस ईमेल को अनदेखा करें।<br />\nआपका खाता तब तक नहीं बनाया जाएगा जब तक आप ऊपर दिए गए लिंक तक पहुँच कर अपना पासवर्ड सेट नहीं करते।"
  time:
    formats:
      devise:
        mailer:
          invitation_instructions:
            accept_until_format: "%B %d, %Y %I:%M %p"

**Comment by scambra** [comment]
Devise doesn't include translations, and I do the same, you can add them to wiki:
https://github.com/scambra/devise_invitable/wiki/I18n
