### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by Medvezo** [scambra/devise_invitable#782]
Hello @scambra!

I have encountered several bugs when using this gem and was wondering whether this project is being maintained or not. I have several _(potentially breaking)_ fixes that I wanted to submit and decided to ask whether you are willing to go through bunch of PRs or whether I should fork the repo and maintain that version.

Also while we are at it: what are the earlist versions of Ruby/Rails/Devise that you support?

Thanks for all the work you have done! :tada:

**Comment by scambra** [comment]
I'm still maintaining this project, mainly fixing reported bugs. Eventually I would like to move inviations to different table, as requested in https://github.com/scambra/devise_invitable/issues/228, but I don't know when I will work on this again. I'm open to PR or add people to project if they want to collaborate.

Devise >= 4.0, ruby >= 2.2, and the rails versions supported by devise. I haven't checked if new devise versions have been released in latest months.

**Comment by Medvezo** [comment]
Thanks!
