### ISSUE TITLE
invitations_controller doesn't take per-model allow_insecure_sign_in_after_accept

### ISSUE THREAD

**Issue by pcrama** [scambra/devise_invitable#790]
Due to the usage of `Devise.allow_insecure_sign_in_after_accept` (instead of `resource.allow_insecure_sign_in_after_accept`?) in [update](https://github.com/scambra/devise_invitable/blob/v2.0.0/app/controllers/devise/invitations_controller.rb#L53), it is useless to use `devise :invitable, allow_insecure_sign_in_after_accept: false` in my model to override the global default for that model only.

Yet the use of `Devise::Models.config` in [models.rb](https://github.com/scambra/devise_invitable/blob/v2.0.0/lib/devise_invitable/models.rb#L389) suggests it should be possible.

Note that this issue is there since a long time (I encountered it in v1.6.1): backporting the fix would be greatly appreciated!

**Comment by scambra** [comment]
Backported to new branch 1-7-stable
