### ISSUE TITLE
What to do when email cannot be delivered (spam etc)?

### ISSUE THREAD

**Issue by viktorsmari** [scambra/devise_invitable#792]
I am using Mailgun and sometimes some emails won't get delivered depending on ISPs.

**Example**:
An admin invites a user, but the email cannot be delivered.

**Question:**
Is it possible for the admin to get the invite URL, so he can send it to the user on Messenger / Slack etc?

What kind of backup strategy do you use for this scenario?

**Sidenote**:
Getting a [new token](http://blog.staub-stefan.ch/rails/coding/devise/2017/09/21/get-invitation-token-manually.html) manually

**Comment by epugh** [comment]
Did you have any luck with this?   I am thinking that I am going to try and intercept the raw token and store it in the database.   I support sending an email with the invite, however, I also want to provide a way to let someone copy the invite and send it as a URL via slack or other tools as well....

**Comment by viktorsmari** [comment]
No I am still waiting for a simple solution.. I also don't want to create a new token after the email has been sent.

**Comment by epugh** [comment]
Check out the issue #852 where I have a...   well..  not terrible... workaround!

**Comment by viktorsmari** [comment]
Cool, I like this solution! https://github.com/scambra/devise_invitable/issues/852#issuecomment-833588227

```ruby
def create
  super do
    flash[:info] = "Share invitation link: #{accept_invitation_url(resource, invitation_token: resource.raw_invitation_token)}"
  end
end
```
