### ISSUE TITLE
How To: Add invite_for in value dynamically

### ISSUE THREAD

**Issue by rahul2240** [scambra/devise_invitable#793]
I want to invite users with a different invite_for value
for example
some user: invitation token should expire in 3 days
other user: invitation token should expire in 4 days

is there any way to do so?

**Comment by scambra** [comment]
It they are the same user model, it isn't possible, as you can see expiration check uses invitation created timestamp (sent is used for backwards compatibility):

https://github.com/scambra/devise_invitable/blob/master/lib/devise_invitable/models.rb#L263

You can have multiple models inheriting from User, using STI, and setup invite_for setting with different values for model.

Or you can add invitation_expired_at column to your model, and some callback to your model, and override invitation_period_valid? to check that timestamp. E.g.:

```ruby
before_invitation_created :setup_expiration

def setup_expiration
  self.invitation_expired_at = self.class.invite_for.days.since
end

def invitation_period_valid?
  return invitation_expired_at.future? if invitation_expired_at?
  super
end
```

**Comment by rahul2240** [comment]
@scambra  thanks for the reply. I thought there may exist something like [this](https://github.com/plataformatec/devise/wiki/How-To:-Add-timeout_in-value-dynamically) where I can use days dynamically
