### ISSUE TITLE
Compat problem with rails 4.2.11 & devise 4.6.2

### ISSUE THREAD

**Issue by joshco** [scambra/devise_invitable#802]
I'm trying to use the 2.x version of invitable.  The readme says it should work including devise 4.6.
I'm getting this error about a conflict with actionmailer, where invitable depends on actionmailer 5.x..  bundle update fails worse.

Is the 2.x version not compatible with Rails 4.x?

````
Bundler could not find compatible versions for gem "actionmailer":
  In snapshot (Gemfile.lock):
    actionmailer (= 4.2.11.1)

  In Gemfile:
    devise_invitable (~> 2.0.0) was resolved to 2.0.1, which depends on
      actionmailer (>= 5.0)

    rails (= 4.2.11.1) was resolved to 4.2.11.1, which depends on
      actionmailer (= 4.2.11.1)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
ubuntu@wsl:~/unx/talker$ bundle list devise
/home/ubuntu/.rvm/gems/ruby-2.5.1/gems/devise-4.6.2
````

**Comment by scambra** [comment]
Devise Invitable 2.x is not compatible with rails 4.2, support was dropped in this PR:
https://github.com/scambra/devise_invitable/pull/785
