### ISSUE TITLE
No route matches [POST] "/invitations/user"

### ISSUE THREAD

**Issue by leekesler** [scambra/devise_invitable#805]
Getting the same error as #198. I'm using the default controller.

# route.rb
Rails.application.routes.draw do
    ....
      devise_for :users, path: "",
                     path_names: { sign_in: "login", sign_out: "logout", registration: "profile" },
                     controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" } # sessions: "users/sessions", passwords: "users/passwords"
  
  devise_scope :user do
    resources :invitations
  end

  ....

**Comment by scambra** [comment]
Can you post rake routes output? At least lines related to devise_invitable controllers

**Comment by leekesler** [comment]
Here is all the lines related to devise_invitable from my rake routes output

`               accept_user_invitation GET      /invitation/accept(.:format)                                                             devise/invitations#edit
               remove_user_invitation GET      /invitation/remove(.:format)                                                             devise/invitations#destroy
                  new_user_invitation GET      /invitation/new(.:format)                                                                devise/invitations#new
                      user_invitation PATCH    /invitation(.:format)                                                                    devise/invitations#update
                                      PUT      /invitation(.:format)                                                                    devise/invitations#update
                                      POST     /invitation(.:format)                                                                    devise/invitations#create
                          invitations GET      /invitations(.:format)                                                                   invitations#index
                                      POST     /invitations(.:format)                                                                   invitations#create
                       new_invitation GET      /invitations/new(.:format)                                                               invitations#new
                      edit_invitation GET      /invitations/:id/edit(.:format)                                                          invitations#edit
                           invitation GET      /invitations/:id(.:format)                                                               invitations#show
                                      PATCH    /invitations/:id(.:format)                                                               invitations#update
                                      PUT      /invitations/:id(.:format)                                                               invitations#update
                                      DELETE   /invitations/:id(.:format)                                                               invitations#destroy
                                 root GET      /      `

**Comment by scambra** [comment]
What are you trying to get with this code?
```ruby
devise_scope :user do
  resources :invitations
end
```
The usual way to change controller for invitations is this way:
```ruby
devise_for :users, controllers: { invitations: 'invitations' }
```
And the usual way to change path name for routes is with path_names in devise_for method, like you did for registrations:
```ruby
devise_for :users, path_name: { invitation: 'custom_path' }
```

**Comment by leekesler** [comment]
I didn't want to change the default views/controllers but for some reason none of the paths were working. So I added resources :invitations which then allowed the paths. I removed the devise_scope part and now it works. Thanks!
