### ISSUE TITLE
Can't add/assign additional user column input in invite?

### ISSUE THREAD

**Issue by Tumble25** [scambra/devise_invitable#808]
Hi All, 

My user table has a `t.integer "role"`, which I would like to assign when inviting a user. However, my role param is not inserted when inviting a user `=> #<User id: 22, email: "test6@hotmail.com", created_at: "2019-10-29 08:31:09", updated_at: "2019-10-29 08:31:09", role: nil>.`

Therefore, I was wondering if it's even possible to add a user column via invite the way I'm trying to do it currently?

views/devise/invitations/new.html.erb

```
<h2><%= t "devise.invitations.new.header" %></h2>

<%= simple_form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :post }) do |f| %>
  <%= f.error_notification %>

  <% resource.class.invite_key_fields.each do |field| -%>
    <div class="form-inputs">
      <%= f.input field %>
    </div>
  <% end -%>

      <%= f.input :role, collection: [:owner, :admin, :employee] %>
  <div class="form-actions">
    <%= f.button :submit, t("devise.invitations.new.submit_button") %>
  </div>
<% end %>
```

controllers/users_controller.rb

```
private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :role)
    end
```

models/user.rb

```
class User < ApplicationRecord
enum role: [:owner, :admin, :employee]
devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :invitable
end

```

**Comment by scambra** [comment]
The right way is explained in README: https://github.com/scambra/devise_invitable#strong-parameters

Add in application controller:

```ruby
before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:invite, keys: [:role])
  end
```

**Comment by Tumble25** [comment]
Dear Scambra, 

thank you so much for the reference to the resource! I didn't link this part of the documentation to the actual invitations. 

It worked, thank you again.
