### ISSUE TITLE
RuntimeError in Devise::InvitationsController#create, Could not find a valid mapping for nil

### ISSUE THREAD

**Issue by Shimol-Khan** [scambra/devise_invitable#821]
I am using devise_invitable gem in my rails 5 application. Every time after submitting the "Send an Invitation" button, I get the error RuntimeError in Devise::InvitationsController#create, Could not find a valid mapping for nil.
**Here is the code of application_controller.rb file:**
<pre>
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    def authenticate_inviter!
        unless current_user.role=='Manager'
            if current_user.role == "Developer"
                redirect_to root_path, :alert => "Access Denied! Only Manager Can Add New Developer"
            end
            super
        end
    end
    protected
    def configure_permitted_parameters
        added_attrs = [ :email, :password, :password_confirmation ]
        devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
        devise_parameter_sanitizer.permit :account_update, keys: added_attrs
        devise_parameter_sanitizer.permit :accept_invitation, keys: [:email]
    end
end
</pre>
**Here is the Code of User.rb:**
<pre>
class User < ApplicationRecord
    include DeviseInvitable::Inviter
    devise :invitable, :database_authenticatable, :registerable,
     :recoverable, :rememberable, :validatable
end
</pre>

**Here is Route.rb:**
<pre>
Rails.application.routes.draw do
    devise_for :users
    root 'dashboard#index'
end
</pre>

I haven't created any custom invitations controller. I just run the following to setup and configure devise_invitable -

- gem 'devise_invitable'

- bundle install

- rails generate devise_invitable:install

- rails generate devise_invitable User

- rails db:migrate

- rails generate devise_invitable:views

- restart the rails server

**Note that everything works fine, but problem is happening after clicking the New Invite link, it sends the invitation link through mailer but after sending the invitation mail, page refreshes saying that RuntimeError in Devise::InvitationsController#create, Could not find a valid mapping for nil.**

**Comment by scambra** [comment]
```ruby
    def authenticate_inviter!
        unless current_user.role=='Manager'
            if current_user.role == "Developer"
                redirect_to root_path, :alert => "Access Denied! Only Manager Can Add New Developer"
            end
            super
        end
    end
```

That method is returning nil for users with Manager role. I don't know why you need unless current_user.role=='Manager' condition. I guess this code should work:

```ruby
    def authenticate_inviter!
        if current_user.role == "Developer"
            redirect_to root_path, :alert => "Access Denied! Only Manager Can Add New Developer"
        end
        super
    end
```

I'm not sure if it's causing that error, because you didn't post a backtrace.

**Comment by Shimol-Khan** [comment]
Yes it works. This error has taken my 2 days while I was using rails for the development of my Project Management App (Final Year Project). Thanks a lot
