### ISSUE TITLE
null slug for invite! user

### ISSUE THREAD

**Issue by ayaesakr** [scambra/devise_invitable#827]
Code:

`User.invite!({email: "example@email.com", name: "John John"}, @user)`

Error generated:

`ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "slug" violates not-null constraint
`

My fix:

```
before_invitation_created :generate_slug

private

  def generate_slug
    return unless slug.nil?

    self.slug = set_slug
  end
```

I want to make sure that a slug is created (if exists) before the invitation is created to avoid the null violation error. Is there a way to have this fixed from within devise_invitable?

_Side note: I am a ruby newbie_

**Comment by scambra** [comment]
There is nothing about slugs in devise invitable, that's a custom code you need to add to your model, nothing related to devise invitable
