### ISSUE TITLE
Unable to use edit registrations path for Provider model

### ISSUE THREAD

**Issue by RailsCod3rFuture** [scambra/devise_invitable#831]
Oddly, the path that allows users to update their password/email/other attributes -- does not work. Even when I use devise_for :providers. The sign in/sign out session paths work. The edit does not. Is there anyway to allow users to edit their password/account settings?

**Comment by scambra** [comment]
Is It working if you remove invitable from your model? And removing gem?

**Comment by RailsCod3rFuture** [comment]
The routes showing are below

/providers/sign_in (devise/session#new)
/providers/sign_in (devise/sessions#create)
/provider/invitation/accept....invitable routes

I see no edit route for the provider.rb model....only for the invitation component of the system new/destroy/edit/update/create

class Provider < ApplicationRecord
  devise :invitable, :database_authenticatable, :rememberable, :trackable, :authentication_keys => [:login]
  has_many :invitations, class_name: 'Provider', as: :invited_by
end

**Comment by RailsCod3rFuture** [comment]
I'm using rails 6 - I will try to update the gem to see if thats the problem

**Comment by RailsCod3rFuture** [comment]
I was using 2.0.0....Testing on 2.0.3

**Comment by RailsCod3rFuture** [comment]
Only devise/sessions#new #create, #destroy are showing for the model. I don't know why....given that database_authenticatable is present in the model's file

**Comment by RailsCod3rFuture** [comment]
After adding registerable to the devise module block. It shows providers/edit/

**Comment by scambra** [comment]
@RailsCod3rFuture That's what I was going to tell you, I think edit routes are added by registerable module, not related to invitable
