### ISSUE TITLE
How can I send additional parameters to the invitation? 

### ISSUE THREAD

**Issue by andrespch** [scambra/devise_invitable#838]
I would like to send out an invitation that contains information about the team a used was invited to join, I tried using the `options` parameter like this:
```ruby
User.invite!({ email:  email }, current_user, options: { team_name: 'my team name' })
```

but I don't know how to access the `options` hash from my view, can you please provide any guidance? I really can't seem to figure this out.

**Comment by scambra** [comment]
Options are passed to deliver_invitation method, which calls invitation_instructions in devise mailer, and pass them as options to devise_mail method (a method defined in Devise gem), so options can be used to change subject, from, or other mail options (anything available in headers argument of mail method in ActionMailer). So you can use your own mailer with devise, and change the invitation_instructions method to make those options available to the view.

Also, you can add them to first hash, next to email, and they will be saved in user attributes (or attr_accessor so it isn't saved to DB), then they will be available in @resource in the mailer view.
