### ISSUE TITLE
Rails 6 upgrade

### ISSUE THREAD

**Issue by vishal-bacancy** [scambra/devise_invitable#840]
getting action mailer issue while upgrading from rails 5.2 to 6

```
Bundler could not find compatible versions for gem "actionmailer":
  In Gemfile:
    devise_invitable (~> 2.0) was resolved to 2.0.3, which depends on
      actionmailer (>= 5.0)

    rails (= 6.0.0) was resolved to 6.0.0, which depends on
      actionmailer (= 6.0.0)
```

getting compatibility issue for action mailer

**Comment by scambra** [comment]
DeviseInvitable requires actionmailer >= 5.0, 6.0.0 is bigger than 5.0, so it should be allowed, I don't kow why bundler reject it. Have you tried bundle update rails actionmailer?

**Comment by vishal-bacancy** [comment]
first, I had replaced "rails" gem from "5.2.2" to "6.0.0" in **Gemfile** which supposed to update and install **actionmailer(6.0.0)**
but when I did the `bundle update rails` it gave me the above error, 
====
Then first, I commented out the gems which had such issues and then I updated to rails 6. finally, I uncommented those gems and did the `bundle install` this is how I updated the rails app for now.
