### ISSUE TITLE
Can't include other attributes in hash for invite! method (undefined method `primary_key' for Hash:Class)

### ISSUE THREAD

**Issue by AndresCarrasquilla96** [scambra/devise_invitable#841]
In our application users belong to program_teams (one user can be included in many program_teams) and they are related via a user_program_team table.
When a user logs into the application he has the option to select which team he wants to work with at that moment. The idea is that the user can invite new or existing users to the program_team he is currently logged into. In the current flow of our application when a new user is invited, first the user record is created, then the user_program_team but it is created inactive since it hasn't accepted the invitation yet:
![imagen](https://user-images.githubusercontent.com/34877052/104761148-122a4300-5728-11eb-9436-a40a653749f6.png)

It is my understanding that the invite! method can recieve a hash with extra attributes, I would like to include the id of the program_team the user was invited to (current_program_team_id) so it is available in my resource and that way when the user accepts the invitation in the accept_resource method I can search for that user_program_team record and make that user active in that program_team.

My problem is that when I try to do this I get the following error:
![imagen](https://user-images.githubusercontent.com/34877052/104761596-bdd39300-5728-11eb-8809-a9751f743a31.png)

**Comment by scambra** [comment]
You're messing with invite! class method which has this signature:
def invite!(attributes = {}, invited_by = nil, options = {}, &block)

You're calling invite! instance method because you already have a user record, so you can set any attribute to that record and then call invite!. Invite! instance method accepts 2 params: invited_by and options (for deliver_invitation method, which will pass options to send_devise_notification method).

**Comment by AndresCarrasquilla96** [comment]
The thing is I need to be able to fetch the new_user_program_team from the accept_resource method to make the user active in the program_team but from there I only have access to the resource object.
![imagen](https://user-images.githubusercontent.com/34877052/104937374-4cd3eb80-5973-11eb-841f-4c9badbe98e8.png)


I tried adding an attr_accesor and added it as a hidden_field on the simple_form
![imagen](https://user-images.githubusercontent.com/34877052/104937437-637a4280-5973-11eb-9858-aaf8752af39a.png)

![imagen](https://user-images.githubusercontent.com/34877052/104937504-755be580-5973-11eb-9947-ebe6f93800c9.png)

![imagen](https://user-images.githubusercontent.com/34877052/104937590-8f95c380-5973-11eb-872b-6430e2495e63.png)

I need a way to include the ` id_program_team_invited_to`  in the `update_resource_params`. I would really appreciate your help.

**Comment by scambra** [comment]
This line will make :id_program_team_invited_to available in update_resource_params:

    devise_parameter_sanitizer.permit :accept_invitation, keys: %i[first_name last_name email id_program_team_invited_to]

So it will be assigned to :id_program_team_invited_to column in user record. Are you getting :id_program_team_invited_to in your request's params? Because you setup f.hidden_field :id_program_team_invited_to, so it will read id_program_team_invited_to from user, I don't know why you need to set id_program_team_invited_to if it's already saved in the user being invited.

**Comment by AndresCarrasquilla96** [comment]
When I click on the accept link I fill the form in which I incuded the `hidden_field` but it has no value set, after I submit it the param appears nil.
![imagen](https://user-images.githubusercontent.com/34877052/105069422-87a75380-5a47-11eb-982c-d003fd389b54.png)

the user table doesn't have that field in the db table, it is linked to the program team through the user_program_team table which has: 
![imagen](https://user-images.githubusercontent.com/34877052/105069950-3e0b3880-5a48-11eb-828d-6f6eebdc7e96.png)

I need a way to include that program_team_id on the invitation so whenever the user accepts an invitation it knows on which team he was invited to so I can make him active there.

**Comment by scambra** [comment]
You can set value in the view, with f.hidden_field :id_program_team_invited_to, value: xxx, but probably is better to not include that value in the view, as it can be changed by user with web inspector, and set it in the controller, such as:

resource_class.accept_invitiation!(update_resource_params.merge(id_program_team_invited_to: xxx))

I don't know how to get xxx value, I guess you need to find it in UserProgramTeam, as you create that record when user is invited

**Comment by AndresCarrasquilla96** [comment]
Yeah, getting that xxx value is exactly my problem, because I can set that value on the controller but since its an attr_accesor by the time the user accepts the invitation that value is lost and in the accep_resource method it is going to be nil.

Isn't there a way to include it in the invitation link...
![imagen](https://user-images.githubusercontent.com/34877052/105099019-981ff400-5a70-11eb-8e51-6fdda0a3a684.png)

So that it says something like `http://localhost:3000/users/invitation/accept?invitation_token=Y5Kzkeqrzf-YsoJmm8Ed&id_program_team_invited_to=xxx ?`

**Comment by scambra** [comment]
Yes, you can include in invitation link if you edit mailer view, and add it to accept invitation url
