### ISSUE TITLE
Feature Request: Be able to recreate the invite Url

### ISSUE THREAD

**Issue by epugh** [scambra/devise_invitable#852]
I've recently added devise_invitable to Quepid (github.com/o19s/quepid), and it's been great to facilitate users joining the tool.

One issue is that often a private deployled copy of Quepid doesn't have email sending set up, however we still want to send invites.

I've spiked out the ability to have a user just copy the invite link in the UI, and send it via other methods like Slack or their own email systems.

My first attempt is just to cache in my own field in the user table the raw token, and then use that:

https://github.com/o19s/quepid/commit/c4f38f886d6b0181b46bc802b72e7a7346e26d12

Is this a reasonable approach?   Is not encrypting the invite token worth a contribution?  Or is my hack worth documenting?

**Comment by epugh** [comment]
This approach _is_ working for me.   Feels a bit "icky", and honestly for this app, I wish I could just turn off the encryption on the token.

**Comment by scambra** [comment]
I think you should be able to display link in response for invite link. For example, [override invitations controller](https://github.com/scambra/devise_invitable#label-Configuring+controllers) to override create method and save link in flash message (or session):

```
def create
  super do
    flash[:info] = "Share invitation link: #{accept_invitation_url(resource, invitation_token: resource.raw_invitation_token)}"
  end
end
```

**Comment by scambra** [comment]
I undestand my suggestion may work to share with slack, but it won't work to have a way to get invitation link later. If that's a needed feature, only way is saving unencrypted token in db, but I won't add a setting to turn off encryption, as devise doesn't have it.

**Comment by epugh** [comment]
thanks!   This library has been great!
