### ISSUE TITLE
Get raw_invitation_token after sending out first invite email (for future use)

### ISSUE THREAD

**Issue by jacobperia** [scambra/devise_invitable#856]
Any help would be greatly appreciated.

I'm trying to get the invitation token to send the **accept_invitation_url** in 4 follow up emails at later dates with the same invitation token but i'm not able to get it to work. It's always nil. I tried using **attr_reader :raw_invitation_token** from what i read online but to no avail.
Is there a workaround for this without generating a new token?

Thanks

**Comment by scambra** [comment]
raw token is not saved, it's only available in the time is generated, so sending future email can't send same invitation token, it should generate and send new token. Only encrypted token is saved, for security, it's a change introduced by devise long time ago, I think the only workaround is saving raw token in database, but there is no setting for that, and I won't add it, you must write your own code to save raw token
