### ISSUE TITLE
Invitation Accept Doesn't Work As Expected With Rails + Turbo

### ISSUE THREAD

**Issue by Petercopter** [scambra/devise_invitable#865]
Steps to reproduce in a Turbo enabled Rails application:

When accepting an invitation, if the form submit fails (passwords don't match), there's no feedback to the user because Turbo expects a `422 Unprocessable Entity` code back in order to re-render. 

To mitigate this there's two options that I know of:
1. Override the invitation controller and change 
```
respond_with_navigational(resource) { render :edit }
```
to
```
respond_with_navigational(resource) { render :edit, status: :unprocessable_entity }
```
2. Change the view form action from
  ```
     <%= simple_form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :put }) do |f| %>
   ```
to
```
<%= simple_form_for(resource, as: resource_name, url: invitation_path(resource_name), data: { turbo: false }, html: { method: :put }) do |f| %>
```

I *think* Devise already made this change, but I haven't looked into in awhile.

**Comment by scambra** [comment]
I think devise did first way, I can see status: :unprocessable_entity in devise controllers, but I don't see turbo: false

Can you send PR with first way to fix it?

**Comment by Petercopter** [comment]
@scambra Sorry I just saw this, thank you very much for the fix!!! 👍  🎉
