### ISSUE TITLE
HowTo: Manually resend invite

### ISSUE THREAD

**Issue by SylarRuby** [scambra/devise_invitable#874]
Hi all. Not issue but was wondering if there was an option for manually resend an invitation? [Been looking at the controller](https://github.com/scambra/devise_invitable/blob/master/app/controllers/devise/invitations_controller.rb) but cannot see how to manually resend.

Do I need to create a PR for this or it's there somewhere already done?

Thanks

**Comment by scambra** [comment]
If a user tries to invitate an already invited user, and [resend_invitation](https://github.com/scambra/devise_invitable#label-Model+configuration) is enabled, new invitation will be sent.

Also you can get the invited user record and call invite!

In both cases, new invitation token is generated, as Devise changed to save a hash of tokens for better security, so raw token is not available to send an email with the same token.

If you want both old and new invitations to work, DeviseInvitable needs to save invitation info in a different table, so an user can have many invitations and all tokens work, as requested few times, e.g. #869 and linked issues, but I couldn't work on it before.

**Comment by SylarRuby** [comment]
Thanks. I guess this would do. I'll reopen if I'm struggling but should be straight forward.
