### ISSUE TITLE
Allow redirecting to a different path than after_sign_out_path_for on invalid token

### ISSUE THREAD

**Issue by Lersoo** [scambra/devise_invitable#879]
Currently, the default behavior for users trying to accept an invitation with an invalid token is to redirect to `after_sign_out_path_for`. This doesn't really work for us, and we'd like to redirect these users to a different path, reserved for invalid invitation tokens. Our `after_sign_out_path_for` is `/user/sign_up` and we don't want invited users to see the sign up form  as they would potentially create a new account instead.

Would it be possible to add the possibility to customize this, either using an overridable method or with a configuration option, just like it's possible to customize `after_invite_path_for` & `after_accept_path_for` ? 

I'm happy to propose a solution, just checking beforehand if that's something that would work for the gem as a whole 🙂 

You can take a look at what I've scribbled until now : https://github.com/scambra/devise_invitable/compare/master...Lersoo:devise_invitable:customizable-invalid-token-path?expand=1

**Comment by scambra** [comment]
You're code looks good, can you send a PR?

**Comment by scambra** [comment]
Never mind, I created a PR from your link and merged
