### ISSUE TITLE
When is the next planned release?

### ISSUE THREAD

**Issue by bunufi** [scambra/devise_invitable#889]
I have noticed that turbo issue, when validation errors are not displayed in "set password" form, is fixed with: https://github.com/scambra/devise_invitable/commit/87228c1feefa0fea1d74f82fe7867111fddc7f91

This is great and is exactly what we need for our app! 

Currently we are requiring `devise_invitable` via git in the gemfile and would like to move to regular releases.  

When the next release is planned?

There is really no rush and I have set up a github notification for this. I just think that this will be very relevant for other stacks with this gem and hotwire. 
Thanks for creating and maintaining this gem!

**Comment by scambra** [comment]
2.0.8 released

**Comment by bunufi** [comment]
Amazing! Thanks a lot for such a quick response and release.
