### ISSUE TITLE
How to report security issues?

### ISSUE THREAD

**Issue by irsdl** [scambra/devise_invitable#914]
Hi @scambra,
@LuciyR and I have identified a security vulnerability in this project and would like to report it privately to minimize potential risks for users. Could you please let us know the best way to communicate this information securely?

Additionally, I recommend adding a security policy to this repository to streamline such reports in the future.

Thanks
Soroush

**Comment by scambra** [comment]
I have enabled reporting security vulnerabilities feature in github, so you can report it in security section of github now
Thanks

**Comment by irsdl** [comment]
@scambra we have reported a security issue using the new setting.
